//	Header generated by Constructor for Palm OS¨ 1.5
//
//	Generated at 6:50:05 PM on Thursday, November 11, 1999
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"NetSample"
//
//	Palm App Version: 		"3.0"



//	Resource: tFRM 1000
#define MainViewForm                              1000
#define MainViewTextField                         1002
#define MainViewScrollbarScrollBar                1003


//	Resource: Talt 1000
#define UnImplementedAlert                        1000
#define UnImplementedOK                           0

//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1002
#define NetLibIncompatibleAlert                   1002
#define NetLibIncompatibleOK                      0

//	Resource: MBAR 1000
#define MainViewMenuMenuBar                       1000

//	Resource: MENU 1200
#define MainviewMiscMenu                          1200
#define MainviewMiscAboutNetSample                1200

//	Resource: MENU 1000
#define MainViewUDPMenu                           1000
#define MainViewUDPDayTime                        1000
#define MainViewUDPDNS                            1001
#define MainViewUDPEcho                           1002
#define MainViewUDPDiscard                        1003
#define MainViewUDPCharGen                        1004
#define MainViewUDPTelnet                         1005
#define MainViewUDPFTP                            1006

//	Resource: MENU 1100
#define MainviewDebugMenu                         1100
#define MainviewDebugConnectLog                   1100
#define MainviewDebugInterfaceInfo                1101
#define MainviewDebugInterfaceStats               1102
#define MainviewDebugIPStats                      1103
#define MainviewDebugICMPStats                    1104
#define MainviewDebugUDPStats                     1105
#define MainviewDebugTCPStats                     1106
#define MainviewDebugTraceAll                     1107
#define MainviewDebugTraceErrMsg                  1108
#define MainviewDebugTraceNone                    1109
#define MainviewDebugTraceDisplay                 1110

//	Resource: MENU 1201
#define EditViewEditMenuMenu                      1201
#define EditViewEditMenuUndo                      1201
#define EditViewEditMenuCut                       1202
#define EditViewEditMenuCopy                      1203
#define EditViewEditMenuPaste                     1204
#define EditViewEditMenuSelectAll                 1205
#define EditViewEditMenuKeyboard                  1207
#define EditViewEditMenuGraffiti                  1208

