//	Header generated by Constructor for Pilot 1.0.2
//
//	Generated at 8:24:40 AM on Thursday, July 08, 1999
//
//	Generated for file: C:\sswork\palm\MSR SDK\Samples\MSR Demo\Src\MSR.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALMPILOT;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Pilot App Name: 		"MSR demo"
//
//	Pilot App Version: 		"1.10"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainStatusButton                          1002	//(Left Origin = 28, Top Origin = 142, Width = 40, Height = 15, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainVersionButton                         1004	//(Left Origin = 81, Top Origin = 142, Width = 40, Height = 15, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainCardInfoField                         1001	//(Left Origin = 1, Top Origin = 18, Width = 150, Height = 122, Usable = 1, Editable = 0, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 300, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainInfoScrollBar                         1003	//(Left Origin = 152, Top Origin = 30, Width = 7, Height = 100, Usable = 1, Value = 0, Minimum Value = 0, Maximum Value = 0, Page Size = 0)


//	Resource: tFRM 1100
#define MSRInfoForm                               1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 155, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define MSRInfoOKButton                           1104	//(Left Origin = 62, Top Origin = 125, Width = 37, Height = 17, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MSRInfoCompanylogBitMap                   1200	//(Left Origin = 0, Top Origin = 17, Bitmap Resource ID = 1200, Usable = 1)
#define MSRInfoMSRLabel                           1101	//(Left Origin = 47, Top Origin = 70, Usable = 1, Font = Standard)
#define MSRInfoVersionLabel                       1102	//(Left Origin = 57, Top Origin = 85, Usable = 1, Font = Standard)


//	Resource: tFRM 1200
#define NoMSRForm                                 1200	//(Left Origin = 2, Top Origin = 5, Width = 154, Height = 135, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define NoMSROKButton                             1204	//(Left Origin = 58, Top Origin = 99, Width = 37, Height = 17, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define NoMSRWarningInfoLabel                     1201	//(Left Origin = 18, Top Origin = 31, Usable = 1, Font = Standard)
#define NoMSRCheckInfoLabel                       1203	//(Left Origin = 18, Top Origin = 51, Usable = 1, Font = Standard)


//	Resource: tFRM 1300
#define SetTrackForm                              1300	//(Left Origin = 1, Top Origin = 2, Width = 158, Height = 151, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define SetTrackOKButton                          1304	//(Left Origin = 27, Top Origin = 128, Width = 45, Height = 18, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define SetTrackCancelButton                      1311	//(Left Origin = 88, Top Origin = 128, Width = 53, Height = 18, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define SetTrackPreambleField                     1305	//(Left Origin = 60, Top Origin = 87, Width = 74, Height = 21, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 16, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define SetTrackPostambleField                    1307	//(Left Origin = 60, Top Origin = 109, Width = 74, Height = 16, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 16, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define SetTrackSeparatorField                    1317	//(Left Origin = 90, Top Origin = 71, Width = 30, Height = 17, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 1, Has Scroll Bar = 0, Numeric = 0)
#define SetTrackTrackSelectionLabel               1301	//(Left Origin = 6, Top Origin = 51, Usable = 1, Font = Standard)
#define SetTrackPreambleLabel                     1303	//(Left Origin = 8, Top Origin = 89, Usable = 1, Font = Standard)
#define SetTrackPostambleLabel                    1306	//(Left Origin = 9, Top Origin = 109, Usable = 1, Font = Standard)
#define SetTrackTerminatorSettingLabel            1312	//(Left Origin = 6, Top Origin = 32, Usable = 1, Font = Standard)
#define SetTrackSeparatorLabel                    1318	//(Left Origin = 7, Top Origin = 70, Usable = 1, Font = Standard)
#define SetTrackSelectionList                     1308	//(Left Origin = 75, Top Origin = 51, Width = 72, Usable = 0, Font = Standard, Visible Items = 0)
#define SetTrackCRLFPushButton                    1313	//(Left Origin = 64, Top Origin = 31, Width = 20, Height = 15, Usable = 1, Group ID = 2, Font = Standard)
#define SetTrackCRPushButton                      1314	//(Left Origin = 85, Top Origin = 31, Width = 20, Height = 15, Usable = 1, Group ID = 2, Font = Standard)
#define SetTrackLFPushButton                      1315	//(Left Origin = 106, Top Origin = 31, Width = 20, Height = 15, Usable = 1, Group ID = 2, Font = Standard)
#define SetTrackNonePushButton                    1316	//(Left Origin = 127, Top Origin = 31, Width = 22, Height = 15, Usable = 1, Group ID = 2, Font = Standard)
#define SetTrackTrackselectionPopTrigger          1302	//(Left Origin = 70, Top Origin = 51, Width = 0, Height = 13, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1308)
#define TrackSettingFormGroupID                   2


//	Resource: tFRM 1400
#define ConfigurationForm                         1400	//(Left Origin = 1, Top Origin = 2, Width = 158, Height = 150, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define ConfigurationOKButton                     1404	//(Left Origin = 27, Top Origin = 128, Width = 45, Height = 18, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ConfigurationCancelButton                 1411	//(Left Origin = 85, Top Origin = 128, Width = 45, Height = 18, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ConfigurationLRCSettingLabel              1401	//(Left Origin = 40, Top Origin = 29, Usable = 1, Font = Standard)
#define ConfigurationDataEditLabel                1418	//(Left Origin = 37, Top Origin = 77, Usable = 1, Font = Standard)
#define ConfigurationNotSendPushButton            1402	//(Left Origin = 28, Top Origin = 45, Width = 45, Height = 15, Usable = 1, Group ID = 4, Font = Standard)
#define ConfigurationSendLRCPushButton            1403	//(Left Origin = 74, Top Origin = 45, Width = 45, Height = 15, Usable = 1, Group ID = 4, Font = Standard)
#define ConfigurationDisablePushButton            1405	//(Left Origin = 15, Top Origin = 92, Width = 38, Height = 15, Usable = 1, Group ID = 5, Font = Standard)
#define ConfigurationMatchPushButton              1406	//(Left Origin = 55, Top Origin = 92, Width = 37, Height = 15, Usable = 1, Group ID = 5, Font = Standard)
#define ConfigurationUnmatchPushButton            1407	//(Left Origin = 93, Top Origin = 92, Width = 38, Height = 15, Usable = 1, Group ID = 5, Font = Standard)
#define ConfigurationFormGroupID                  4
#define ConfigurationFormGroupID2                 5


//	Resource: tFRM 1500
#define AddedFieldForm                            1500	//(Left Origin = 1, Top Origin = 29, Width = 157, Height = 130, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AddedFieldOKButton                        1507	//(Left Origin = 28, Top Origin = 112, Width = 36, Height = 14, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AddedFieldCancelButton                    1508	//(Left Origin = 90, Top Origin = 112, Width = 36, Height = 14, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AddedFieldAddedField                      1502	//(Left Origin = 2, Top Origin = 27, Width = 153, Height = 72, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 160, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define AddedFieldAddedFieldLabel                 1501	//(Left Origin = 57, Top Origin = 7, Usable = 1, Font = Standard)


//	Resource: tFRM 1600
#define FlexibleFieldForm                         1600	//(Left Origin = 1, Top Origin = 1, Width = 157, Height = 158, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define FlexibleFieldOKButton                     1607	//(Left Origin = 30, Top Origin = 137, Width = 36, Height = 14, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define FlexibleFieldCancelButton                 1608	//(Left Origin = 92, Top Origin = 137, Width = 36, Height = 14, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define FlexibleFieldFlexibleField                1606	//(Left Origin = 5, Top Origin = 20, Width = 149, Height = 114, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 300, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define FlexibleFieldFlexiblefieldLabel           1605	//(Left Origin = 53, Top Origin = 6, Usable = 1, Font = Standard)


//	Resource: tFRM 1700
#define SendCommandForm                           1700	//(Left Origin = 1, Top Origin = 20, Width = 158, Height = 139, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define SendCommandOKButton                       1707	//(Left Origin = 28, Top Origin = 120, Width = 36, Height = 14, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define SendCommandCancelButton                   1708	//(Left Origin = 90, Top Origin = 120, Width = 36, Height = 14, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define SendCommandSendCommandField               1704	//(Left Origin = 2, Top Origin = 27, Width = 153, Height = 88, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 240, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define SendCommandUnnamed1703Label               1703	//(Left Origin = 44, Top Origin = 8, Usable = 1, Font = Standard)


//	Resource: tFRM 1800
#define NoMSRLibraryForm                          1800	//(Left Origin = 2, Top Origin = 5, Width = 154, Height = 135, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define NoMSRLibraryOKButton                      1804	//(Left Origin = 58, Top Origin = 99, Width = 37, Height = 17, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define NoMSRLibraryWarningInfoLabel              1801	//(Left Origin = 8, Top Origin = 31, Usable = 1, Font = Standard)
#define NoMSRLibraryCheckInfoLabel                1803	//(Left Origin = 30, Top Origin = 51, Usable = 1, Font = Standard)


//	Resource: tFRM 1900
#define GenericDecoderForm                        1900	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define GenericDecoderOKButton                    1901	//(Left Origin = 31, Top Origin = 138, Width = 36, Height = 14, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GenericDecoderCancelButton                1902	//(Left Origin = 83, Top Origin = 138, Width = 36, Height = 14, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GenericDecoderSS_B1Field                  1906	//(Left Origin = 32, Top Origin = 56, Width = 24, Height = 13, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define GenericDecoderSS_A1Field                  1908	//(Left Origin = 33, Top Origin = 75, Width = 24, Height = 13, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define GenericDecoderES_B1Field                  1910	//(Left Origin = 33, Top Origin = 94, Width = 24, Height = 13, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define GenericDecoderES_A1Field                  1912	//(Left Origin = 32, Top Origin = 114, Width = 24, Height = 13, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define GenericDecoderSS_B2Field                  1915	//(Left Origin = 70, Top Origin = 56, Width = 24, Height = 13, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define GenericDecoderSS_B3Field                  1916	//(Left Origin = 108, Top Origin = 56, Width = 24, Height = 13, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define GenericDecoderSS_A2Field                  1917	//(Left Origin = 70, Top Origin = 75, Width = 24, Height = 13, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define GenericDecoderES_B2Field                  1918	//(Left Origin = 70, Top Origin = 94, Width = 24, Height = 13, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define GenericDecoderES_A2Field                  1919	//(Left Origin = 70, Top Origin = 114, Width = 24, Height = 13, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define GenericDecoderSS_A3Field                  1920	//(Left Origin = 108, Top Origin = 75, Width = 24, Height = 13, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define GenericDecoderES_B3Field                  1921	//(Left Origin = 108, Top Origin = 94, Width = 24, Height = 13, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define GenericDecoderES_A3Field                  1922	//(Left Origin = 108, Top Origin = 114, Width = 24, Height = 13, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define GenericDecoderDecoderModeLabel            1903	//(Left Origin = 4, Top Origin = 17, Usable = 1, Font = Standard)
#define GenericDecoderTrack1FormatLabel           1904	//(Left Origin = 32, Top Origin = 30, Usable = 1, Font = Standard)
#define GenericDecoderSS_BLabel                   1905	//(Left Origin = 6, Top Origin = 56, Usable = 1, Font = Standard)
#define GenericDecoderSS_ALabel                   1907	//(Left Origin = 6, Top Origin = 75, Usable = 1, Font = Standard)
#define GenericDecoderES_BLabel                   1909	//(Left Origin = 6, Top Origin = 95, Usable = 1, Font = Standard)
#define GenericDecoderES_ALabel                   1911	//(Left Origin = 5, Top Origin = 115, Usable = 1, Font = Standard)
#define GenericDecoderTrack2Label                 1913	//(Left Origin = 72, Top Origin = 30, Usable = 1, Font = Standard)
#define GenericDecoderTrack3Label                 1914	//(Left Origin = 106, Top Origin = 30, Usable = 1, Font = Standard)
#define GenericDecoderModeList                    1923	//(Left Origin = 62, Top Origin = 18, Width = 80, Usable = 0, Font = Standard, Visible Items = 0)
#define GenericDecoderFormat1List                 1925	//(Left Origin = 28, Top Origin = 42, Width = 40, Usable = 0, Font = Standard, Visible Items = 0)
#define GenericDecoderFormat2List                 1927	//(Left Origin = 69, Top Origin = 42, Width = 40, Usable = 0, Font = Standard, Visible Items = 0)
#define GenericDecoderFormat3List                 1929	//(Left Origin = 104, Top Origin = 42, Width = 40, Usable = 0, Font = Standard, Visible Items = 0)
#define GenericDecoderModePopTrigger              1924	//(Left Origin = 62, Top Origin = 17, Width = 0, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1923)
#define GenericDecoderFormat1PopTrigger           1926	//(Left Origin = 28, Top Origin = 42, Width = 0, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1925)
#define GenericDecoderFormat2PopTrigger           1928	//(Left Origin = 69, Top Origin = 42, Width = 0, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1927)
#define GenericDecoderFormat3PopTrigger           1930	//(Left Origin = 106, Top Origin = 42, Width = 0, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1929)


//	Resource: tFRM 2000
#define ReservedCharacterForm                     2000	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define ReservedCharacterOKButton                 2001	//(Left Origin = 32, Top Origin = 133, Width = 36, Height = 14, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ReservedCharacterCancelButton             2002	//(Left Origin = 88, Top Origin = 133, Width = 36, Height = 14, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ReservedCharacterPattern1Field            2008	//(Left Origin = 54, Top Origin = 36, Width = 25, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ReservedCharacterPattern2Field            2009	//(Left Origin = 54, Top Origin = 50, Width = 25, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ReservedCharacterPattern3Field            2010	//(Left Origin = 54, Top Origin = 64, Width = 25, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ReservedCharacterPattern4Field            2011	//(Left Origin = 54, Top Origin = 78, Width = 25, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ReservedCharacterPattern5Field            2012	//(Left Origin = 54, Top Origin = 92, Width = 25, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ReservedCharacterPattern6Field            2013	//(Left Origin = 54, Top Origin = 106, Width = 25, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ReservedCharacterChar1Field               2014	//(Left Origin = 102, Top Origin = 36, Width = 25, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ReservedCharacterChar2Field               2015	//(Left Origin = 102, Top Origin = 50, Width = 25, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ReservedCharacterChar3Field               2016	//(Left Origin = 102, Top Origin = 64, Width = 25, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ReservedCharacterChar4Field               2017	//(Left Origin = 102, Top Origin = 78, Width = 25, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ReservedCharacterChar5Field               2018	//(Left Origin = 102, Top Origin = 92, Width = 25, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ReservedCharacterChar6Field               2019	//(Left Origin = 102, Top Origin = 106, Width = 25, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ReservedCharacterPatternLabel             2006	//(Left Origin = 54, Top Origin = 18, Usable = 1, Font = Standard)
#define ReservedCharacterCharacterLabel           2007	//(Left Origin = 102, Top Origin = 18, Usable = 1, Font = Standard)
#define ReservedCharacterFormatLabel              2029	//(Left Origin = 7, Top Origin = 18, Usable = 1, Font = Standard)
#define ReservedCharacterFormat1List              2003	//(Left Origin = 9, Top Origin = 36, Width = 40, Usable = 0, Font = Standard, Visible Items = 0)
#define ReservedCharacterFormat2List              2005	//(Left Origin = 9, Top Origin = 50, Width = 40, Usable = 0, Font = Standard, Visible Items = 0)
#define ReservedCharacterFormat3List              2021	//(Left Origin = 9, Top Origin = 64, Width = 40, Usable = 0, Font = Standard, Visible Items = 0)
#define ReservedCharacterFormat4List              2023	//(Left Origin = 9, Top Origin = 78, Width = 40, Usable = 0, Font = Standard, Visible Items = 0)
#define ReservedCharacterFormat5List              2025	//(Left Origin = 9, Top Origin = 92, Width = 40, Usable = 0, Font = Standard, Visible Items = 0)
#define ReservedCharacterFormat6List              2027	//(Left Origin = 9, Top Origin = 106, Width = 40, Usable = 0, Font = Standard, Visible Items = 0)
#define ReservedCharacterFormat1PopTrigger        2004	//(Left Origin = 7, Top Origin = 36, Width = 0, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2003)
#define ReservedCharacterFormat2PopTrigger        2020	//(Left Origin = 7, Top Origin = 50, Width = 0, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2005)
#define ReservedCharacterFormat3PopTrigger        2022	//(Left Origin = 7, Top Origin = 64, Width = 0, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2021)
#define ReservedCharacterFormat4PopTrigger        2024	//(Left Origin = 7, Top Origin = 78, Width = 0, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2023)
#define ReservedCharacterFormat5PopTrigger        2026	//(Left Origin = 7, Top Origin = 92, Width = 0, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2025)
#define ReservedCharacterFormat6PopTrigger        2028	//(Left Origin = 8, Top Origin = 106, Width = 0, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2027)


//	Resource: tFRM 2100
#define LowBatteryForm                            2100	//(Left Origin = 2, Top Origin = 5, Width = 154, Height = 135, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define LowBatteryOKButton                        2104	//(Left Origin = 58, Top Origin = 99, Width = 37, Height = 17, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define LowBatteryWarningInfoLabel                2101	//(Left Origin = 16, Top Origin = 31, Usable = 1, Font = Standard)
#define LowBatteryCheckInfoLabel                  2103	//(Left Origin = 30, Top Origin = 51, Usable = 1, Font = Standard)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: MBAR 1000
#define MainFormMenuBar                           1000

//	Resource: MENU 1200
#define MainOptionsMenu                           1200
#define MainOptionsSetDefault                     1200
#define MainOptionsSelfDiagnose                   1201
#define MainOptionsBufferedMode                   1202
#define MainOptionsUnbufferedMode                 1203
#define MainOptionsArmtoRead                      1204
#define MainOptionsReadBufferedMSR                1205
#define MainOptionsGetAllBufferedData             1206
#define MainOptionsGetBufferedTrack1              1207
#define MainOptionsGetBufferedTrack2              1208
#define MainOptionsGetBufferedTrack3              1209
#define MainOptionsConfiguratorSetting            1210
#define MainOptionsAboutMSRdemo                   1211

//	Resource: MENU 1000
#define MSRSettingMenu                            1000
#define MSRSettingTrackSetting                    1000
#define MSRSettingConfiguration                   1001
#define MSRSettingAddedField                      1002
#define MSRSettingSendCommand                     1003
#define MSRSettingFlexibleField                   1004
#define MSRSettingGenericDecoder                  1005
#define MSRSettingReservedCharacter               1006

//	Resource: PICT 1200
#define SymbolLogoBitmap                          1200