//	Header generated by Constructor for Palm OS¨ 1.5
//
//	Generated at 6:51:20 PM on Thursday, November 11, 1999
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"RockMusic"
//
//	Palm App Version: 		"3.0"



//	Resource: tFRM 1000
#define RockMusicMainForm                         1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define RockMusicMainPlayButton                   1001	//(Left Origin = 9, Top Origin = 131, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define RockMusicMainInstallButton                1003	//(Left Origin = 61, Top Origin = 131, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define RockMusicMainInputGadget                  1002	//(Left Origin = 7, Top Origin = 24, Width = 145, Height = 99, Usable = 1)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1101
#define SaySomethingAlert                         1101
#define SaySomethingOK                            0

