/***********************************************************************
 *
 * Copyright (c) 1999, TRG, All Rights Reserved
 *
 * PROJECT:         Nomad CF demo
 *
 * FILE:     cmd.h
 *
 * DESCRIPTION:   header for cmd.h
 *
 * AUTHOR: Trevor Meyer         
 *
 * DATE: 8/10/99           
 *
 **********************************************************************/
#ifndef _CMD_H_
#define _CMD_H_

void CMDInit(void);
void CMDProcess(char chr);

#endif
