//	Header generated by Constructor for Pilot 1.0.2
//
//	Generated at 9:16:08 AM on Thursday, August 12, 1999
//
//	Generated for file: Q:\SPT1700\sdk200b\Samples\S24 Samples\Client\CaDmv\Rsc\CaDmv.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALMPILOT;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Pilot App Name: 		"CaDmv"
//
//	Pilot App Version: 		"1.0"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainSubmitButton                          1012	//(Left Origin = 104, Top Origin = 138, Width = 41, Height = 12, Usable = 1, Anchor Left = 0, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainSwipeButton                           1013	//(Left Origin = 11, Top Origin = 138, Width = 87, Height = 12, Usable = 1, Anchor Left = 0, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainStatusField                           1007	//(Left Origin = 9, Top Origin = 12, Width = 141, Height = 16, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 40, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainName1Field                            1015	//(Left Origin = 34, Top Origin = 32, Width = 122, Height = 18, Usable = 1, Editable = 0, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 30, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainCityField                             1017	//(Left Origin = 34, Top Origin = 89, Width = 66, Height = 14, Usable = 1, Editable = 0, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 16, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainName2Field                            1018	//(Left Origin = 34, Top Origin = 45, Width = 122, Height = 18, Usable = 1, Editable = 0, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 30, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainAddr1Field                            1019	//(Left Origin = 33, Top Origin = 57, Width = 122, Height = 18, Usable = 1, Editable = 0, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 30, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainAddr2Field                            1020	//(Left Origin = 34, Top Origin = 68, Width = 122, Height = 18, Usable = 1, Editable = 0, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 30, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainStateField                            1021	//(Left Origin = 128, Top Origin = 89, Width = 20, Height = 14, Usable = 1, Editable = 0, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 1, Has Scroll Bar = 0, Numeric = 0)
#define MainHieghtField                           1022	//(Left Origin = 87, Top Origin = 106, Width = 17, Height = 11, Usable = 1, Editable = 0, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainWieghtField                           1023	//(Left Origin = 130, Top Origin = 107, Width = 17, Height = 11, Usable = 1, Editable = 0, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainHairField                             1024	//(Left Origin = 82, Top Origin = 121, Width = 17, Height = 11, Usable = 1, Editable = 0, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainEyesField                             1025	//(Left Origin = 130, Top Origin = 121, Width = 17, Height = 11, Usable = 1, Editable = 0, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainSexField                              1026	//(Left Origin = 45, Top Origin = 106, Width = 11, Height = 11, Usable = 1, Editable = 0, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainUnnamed1001Label                      1001	//(Left Origin = 7, Top Origin = 69, Usable = 1, Font = Standard)
#define MainUnnamed1002Label                      1002	//(Left Origin = 60, Top Origin = 121, Usable = 1, Font = Standard)
#define MainUnnamed1003Label                      1003	//(Left Origin = 2, Top Origin = 31, Usable = 1, Font = Standard)
#define MainUnnamed1004Label                      1004	//(Left Origin = 2, Top Origin = 45, Usable = 1, Font = Standard)
#define MainUnnamed1005Label                      1005	//(Left Origin = 104, Top Origin = 121, Usable = 1, Font = Standard)
#define MainUnnamed1006Label                      1006	//(Left Origin = 7, Top Origin = 57, Usable = 1, Font = Standard)
#define MainUnnamed1008Label                      1008	//(Left Origin = 12, Top Origin = 89, Usable = 1, Font = Standard)
#define MainUnnamed1009Label                      1009	//(Left Origin = 25, Top Origin = 106, Usable = 1, Font = Standard)
#define MainUnnamed1010Label                      1010	//(Left Origin = 109, Top Origin = 106, Usable = 1, Font = Standard)
#define MainUnnamed1011Label                      1011	//(Left Origin = 62, Top Origin = 106, Usable = 1, Font = Standard)
#define MainUnnamed1016Label                      1016	//(Left Origin = 111, Top Origin = 89, Usable = 1, Font = Standard)


//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1101	//(Left Origin = 20, Top Origin = 120, Width = 120, Height = 31, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define AboutSymbolLogoBitMap                     1100	//(Left Origin = 0, Top Origin = 13, Bitmap Resource ID = 1100, Usable = 1)
#define AboutMSDriverField                        1104	//(Left Origin = 104, Top Origin = 87, Width = 50, Height = 13, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define AboutRFDriverField                        1107	//(Left Origin = 104, Top Origin = 103, Width = 50, Height = 13, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define AboutUnnamed1102Label                     1102	//(Left Origin = 24, Top Origin = 87, Usable = 1, Font = Standard)
#define AboutUnnamed1105Label                     1105	//(Left Origin = 58, Top Origin = 103, Usable = 1, Font = Standard)
#define AboutCopyrightLabel                       1109	//(Left Origin = 1, Top Origin = 63, Usable = 1, Font = Standard)
#define AboutCopyrighttooLabel                    1110	//(Left Origin = 51, Top Origin = 73, Usable = 1, Font = Standard)


//	Resource: tFRM 1200
#define ImageForm                                 1200	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 0, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define ImageOKButton                             1201	//(Left Origin = 0, Top Origin = 19, Width = 160, Height = 138, Usable = 1, Anchor Left = 0, Frame = 0, Non-bold Frame = 0, Font = Bold)
#define ImageImageBitMap                          1300	//(Left Origin = 0, Top Origin = 17, Bitmap Resource ID = 1300, Usable = 1)


//	Resource: Talt 1000
#define BatteryErrorAlert                         1000
#define BatteryErrorOK                            0

//	Resource: Talt 1500
#define GeneralAlert                              1500
#define GeneralOK                                 0

//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: MBAR 1000
#define MainMenuBar                               1000

//	Resource: MENU 1000
#define OptionsMenu                               1000
#define OptionsAbout                              1000	// Command Key: A

//	Resource: tSTR 1000
#define MainFormHelpString                        1000	// "Test and Control of SE 1223 Scanner using SSI. Configure SE 1223 as follows to operate correctly.  This may be done using Parameter Barcodes.   1. Set All Defaults Parameter 2. Triggering Mode = HOST 3. Send Packeted Decode Data"

//	Resource: PICT 1100
#define SymbolLogoBitmap                          1100
//	Resource: PICT 1200
#define dcatBitmap                                1200
//	Resource: PICT 1000
#define myvanBitmap                               1000
//	Resource: PICT 1300
#define defaultBitmap                             1300