//	Header generated by Constructor for Pilot 1.0.2
//
//	Generated at 5:14:44 PM on Tuesday, January 26, 1999
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALMPILOT;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Pilot App Name: 		"SampleDial"
//
//	Pilot App Version: 		"1.0"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define Main1Button                               1001	//(Left Origin = 1, Top Origin = 50, Width = 52, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define Main2Button                               1002	//(Left Origin = 54, Top Origin = 50, Width = 52, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define Main3Button                               1003	//(Left Origin = 107, Top Origin = 50, Width = 52, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define Main4Button                               1004	//(Left Origin = 1, Top Origin = 72, Width = 52, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define Main5Button                               1005	//(Left Origin = 54, Top Origin = 72, Width = 52, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define Main6Button                               1006	//(Left Origin = 107, Top Origin = 72, Width = 52, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define Main7Button                               1007	//(Left Origin = 1, Top Origin = 94, Width = 52, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define Main8Button                               1008	//(Left Origin = 54, Top Origin = 94, Width = 52, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define Main9Button                               1009	//(Left Origin = 107, Top Origin = 94, Width = 52, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define Main0Button                               1010	//(Left Origin = 54, Top Origin = 116, Width = 52, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainStarButton                            1011	//(Left Origin = 1, Top Origin = 116, Width = 52, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainPoundButton                           1012	//(Left Origin = 107, Top Origin = 116, Width = 52, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainSendButton                            1016	//(Left Origin = 1, Top Origin = 138, Width = 52, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainClearButton                           1017	//(Left Origin = 54, Top Origin = 138, Width = 52, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainEndButton                             1018	//(Left Origin = 107, Top Origin = 138, Width = 52, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)


//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 3, Top Origin = 28, Width = 154, Height = 130, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1101	//(Left Origin = 61, Top Origin = 115, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutLogoBitMap                           1000	//(Left Origin = 2, Top Origin = 14, Bitmap Resource ID = 1000, Usable = 1)
#define AboutVersionLabelLabel                    1103	//(Left Origin = 51, Top Origin = 92, Usable = 1, Font = Standard)
#define AboutVersionStrLabel                      1104	//(Left Origin = 89, Top Origin = 92, Usable = 1, Font = Standard)


//	Resource: MBAR 1000
#define MainFormMenuBar                           1000

//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAboutSampleDialer              1000
#define MainOptionsInsertTimedPause               1002
#define MainOptionsInsertUserPause                1003

//	Resource: PICT 1000
#define Bitmap                                    1000