//	Header generated by Constructor for Pilot 1.0.2
//
//	Generated at 2:41:21 PM on Wednesday, January 20, 1999
//
//	Generated for file: C:\WINNT\Profiles\c_mweiss\Desktop\SimonSez\Src\Simon.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALMPILOT;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Pilot App Name: 		"Simon Sez"
//
//	Pilot App Version: 		"1.1"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainHowToPlayButton                       1001	//(Left Origin = 3, Top Origin = 139, Width = 60, Height = 14, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainNewGameButton                         1005	//(Left Origin = 107, Top Origin = 139, Width = 50, Height = 14, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainRedPushButton                         1002	//(Left Origin = 51, Top Origin = 46, Width = 60, Height = 20, Usable = 1, Group ID = 0, Font = Large)
#define MainOrangePushButton                      1003	//(Left Origin = 17, Top Origin = 73, Width = 60, Height = 20, Usable = 1, Group ID = 0, Font = Large)
#define MainGreenPushButton                       1004	//(Left Origin = 85, Top Origin = 73, Width = 60, Height = 20, Usable = 1, Group ID = 0, Font = Large)
#define SimonSezFormGroupID                       0


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1300
#define AboutBoxAlert                             1300
#define AboutBoxOK                                0

//	Resource: Talt 1400
#define HowToPlayAlert                            1400
#define HowToPlayOK                               0

//	Resource: Talt 1000
#define ReadyBeginAlert                           1000
#define ReadyBeginBegin                           0
#define ReadyBeginCancel                          1

//	Resource: Talt 1100
#define YourScoreAlert                            1100
#define YourScoreOK                               0

//	Resource: Talt 1200
#define PressNewGameAlert                         1200
#define PressNewGameOK                            0

//	Resource: MBAR 1000
#define MainFormMenuBar                           1000

//	Resource: MENU 1000
#define OptionsMenu                               1000
#define OptionsAboutSimonSez                      1000
