//	Header generated by Constructor for Pilot 1.0.2
//
//	Generated at 2:19:21 PM on Wednesday, July 07, 1999
//
//	Generated for file: C:\sswork\palm\MSR SDK\Samples\MSR Sample\Src\msr_sample.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALMPILOT;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Pilot App Name: 		"MSR sample"
//
//	Pilot App Version: 		"1.5"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainCardInfoField                         1001	//(Left Origin = 3, Top Origin = 17, Width = 154, Height = 130, Usable = 1, Editable = 0, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 300, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)


//	Resource: tFRM 1100
#define MSRInfoForm                               1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 155, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define MSRInfoOKButton                           1104	//(Left Origin = 62, Top Origin = 124, Width = 37, Height = 17, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MSRInfoCompanylogBitMap                   1200	//(Left Origin = 0, Top Origin = 15, Bitmap Resource ID = 1200, Usable = 1)
#define MSRInfoMSRLabel                           1101	//(Left Origin = 56, Top Origin = 70, Usable = 1, Font = Standard)
#define MSRInfoVersionLabel                       1102	//(Left Origin = 58, Top Origin = 85, Usable = 1, Font = Standard)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: MBAR 1000
#define MainFormMenuBar                           1000

//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAboutMSRSample                 1000

//	Resource: PICT 1200
#define SymbolLogoBitmap                          1200