//	Header generated by Constructor for Pilot 1.0.2
//
//	Generated at 2:18:20 PM on Thursday, February 25, 1999
//
//	Generated for file: C:\Program Files\Metrowerks\CodeWarrior\SCANNER_SDK_1.29\Samples\SimpleScan\Rsc\RESOURCE.FRK\SimpleScanRsc.rsr
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALMPILOT;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Pilot App Name: 		"SimpleScan"
//
//	Pilot App Version: 		"1.29"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 1000, Menu Bar ID = 1000, Default Button ID = 0)
#define MainSCANButton                            1004	//(Left Origin = 56, Top Origin = 140, Width = 41, Height = 12, Usable = 1, Anchor Left = 0, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainScandataField                         1002	//(Left Origin = 55, Top Origin = 80, Width = 100, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainBarTypeField                          1009	//(Left Origin = 55, Top Origin = 67, Width = 100, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainBarTypeLabel                          1005	//(Left Origin = 4, Top Origin = 67, Usable = 1, Font = Bold)
#define MainBarDataLabel                          1006	//(Left Origin = 4, Top Origin = 80, Usable = 1, Font = Bold)


//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1101	//(Left Origin = 60, Top Origin = 141, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutDecoderField                         1103	//(Left Origin = 78, Top Origin = 96, Width = 75, Height = 13, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define AboutScanManagerField                     1105	//(Left Origin = 100, Top Origin = 111, Width = 53, Height = 13, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define AboutPortDriverField                      1107	//(Left Origin = 90, Top Origin = 124, Width = 63, Height = 13, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define AboutDecoderLabel                         1102	//(Left Origin = 4, Top Origin = 96, Usable = 1, Font = Standard)
#define AboutScanManagerLabel                     1104	//(Left Origin = 4, Top Origin = 110, Usable = 1, Font = Standard)
#define AboutPortDriverLabel                      1106	//(Left Origin = 4, Top Origin = 124, Usable = 1, Font = Standard)
#define AboutUnnamed1108Label                     1108	//(Left Origin = 17, Top Origin = 33, Usable = 1, Font = Bold)
#define AboutCopyrightLabel                       1109	//(Left Origin = 4, Top Origin = 68, Usable = 1, Font = Standard)
#define AboutCopyrighttooLabel                    1110	//(Left Origin = 4, Top Origin = 82, Usable = 1, Font = Standard)


//	Resource: Talt 1000
#define BatteryErrorAlert                         1000
#define BatteryErrorOK                            0

//	Resource: MBAR 1000
#define MainMenuBar                               1000

//	Resource: MENU 1000
#define OptionsMenu                               1000
#define OptionsResetDefaults                      1000	// Command Key: R
#define OptionsAbout                              1002	// Command Key: A

//	Resource: tSTR 1000
#define MainFormHelpString                        1000	// "Test and Control of SE 1223 Scanner using SSI. Configure SE 1223 as follows to operate correctly.  This may be done using Parameter Barcodes.   1. Set All Defaults Parameter 2. Triggering Mode = HOST 3. Send Packeted Decode Data"

//	Resource: tSTR 1200
#define PreferencesFormHelpString                 1200	// ""

//	Resource: tSTR 1300
#define HardwareFormHelpString                    1300	// ""

//	Resource: tSTR 1700
#define UPCMoreFormHelpString                     1700	// ""

//	Resource: tSTR 1800
#define Code128FormHelpString                     1800	// ""

//	Resource: tSTR 1900
#define Code39FormHelpString                      1900	// ""

//	Resource: tSTR 2000
#define MoreCode39FormHelpString                  2000	// ""

//	Resource: tSTR 2100
#define Code93FormHelpString                      2100	// ""

//	Resource: tSTR 2200
#define I2of5FormHelpString                       2200	// ""

//	Resource: tSTR 2300
#define D2of5FormHelpString                       2300	// ""

//	Resource: tSTR 2400
#define CodabarFormHelpString                     2400	// ""

//	Resource: tSTR 2500
#define MSIPlesseyFormHelpString                  2500	// ""

//	Resource: tSTR 2600
#define CodeFormatFormHelpString                  2600	// ""

//	Resource: tSTR 1600
#define UPCFormHelpString                         1600	// ""

//	Resource: tSTR 1500
#define TriggerFormHelpString                     1500	// ""

//	Resource: tSTR 2800
#define BeepFrequencySettingFormHelpString        2800	// ""

//	Resource: tSTR 2900
#define BeepDurationSettingsFormHelpString        2900	// ""

//	Resource: tSTR 3000
#define DecoderSettingsFormHelpString             3000	// ""

//	Resource: tSTR 3100
#define BCTypeNotApplicableString                 3100	// "Not Applicable"

//	Resource: tSTR 3200
#define BCTypeCode39String                        3200	// "Code 39"

//	Resource: tSTR 3300
#define BCTypeCodabarString                       3300	// "Codabar"

//	Resource: tSTR 3400
#define BCTypeCode128String                       3400	// "Code 128"

//	Resource: tSTR 3500
#define BCTypeDiscrete2Of5String                  3500	// "Discrete 2 of 5"

//	Resource: tSTR 3600
#define BCTypeIATA2of5String                      3600	// "IATA 2 of 5"

//	Resource: tSTR 3700
#define BCTypeInterleaved2Of5String               3700	// "Interleaved 2 of 5"

//	Resource: tSTR 3800
#define BCTypeCode93String                        3800	// "Code 93"

//	Resource: tSTR 3900
#define BCTypeUPCAString                          3900	// "UPC A"

//	Resource: tSTR 4000
#define BCTypeUPCA2SuppsString                    4000	// "UPC A with 2 Supps."

//	Resource: tSTR 4100
#define BCTypeUPCA5SuppsString                    4100	// "UPC A with 5 Supps."

//	Resource: tSTR 4200
#define BCTypeUPCEOString                         4200	// "UPC EO"

//	Resource: tSTR 4300
#define BCTypeUPCEO2SuppsString                   4300	// "UPC EO with 2 Supps."

//	Resource: tSTR 4400
#define BCTypeUPCEO5SuppsString                   4400	// "UPC EO with 5 Supps."

//	Resource: tSTR 4500
#define BCTypeEAN8String                          4500	// "EAN 8"

//	Resource: tSTR 4600
#define BCTypeEAN82SuppsString                    4600	// "EAN 8 with 2 Supps."

//	Resource: tSTR 4700
#define BCTypeEAN85SuppsString                    4700	// "EAN 8 with 5 Supps."

//	Resource: tSTR 4800
#define BCTypeEAN13String                         4800	// "EAN 13"

//	Resource: tSTR 4900
#define BCTypeEAN132SuppsString                   4900	// "EAN 13 with 2 Supps."

//	Resource: tSTR 5000
#define BCTypeEAN135SuppsString                   5000	// "EAN 13 with 5 Supps."

//	Resource: tSTR 5100
#define BCTypeMSIPlesseyString                    5100	// "MSI Plessey"

//	Resource: tSTR 5200
#define BCTypeEAN128String                        5200	// "EAN 128"

//	Resource: tSTR 5300
#define BCTypeUPCE1String                         5300	// "UPC E1"

//	Resource: tSTR 5400
#define BCTypeUPCE12SuppsString                   5400	// "UPC E1 with 2 Supps."

//	Resource: tSTR 5500
#define BCTypeUPCE15SuppsString                   5500	// "UPC E1 with 5 Supps."

//	Resource: tSTR 5600
#define BCTypeTriopticCode39String                5600	// "Trioptic Code 39"

//	Resource: tSTR 5700
#define BCTypeBooklandEANString                   5700	// "Bookland EAN"

//	Resource: tSTR 5800
#define BCTypeCouponCodeString                    5800	// "Coupon Code"
