//	Header generated by Constructor for Palm OS¨ 1.5
//
//	Generated at 12:50:31 AM on Thursday, July 27, 2000
//
//	Generated for file: C:\BIBLE\CODE\CH20\COLORTEST\cw\Rsc\colortest.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"Color Test"
//
//	Palm App Version: 		"1.0"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainCustomPaletteCheckbox                 1008	//(Left Origin = 2, Top Origin = 148, Width = 120, Height = 12, Usable = 0, Selected = 0, Group ID = 0, Font = Bold)
#define MainEarthSingleBitMap                     2000	//(Left Origin = 8, Top Origin = 25, Bitmap Resource ID = 2000, Usable = 0)
#define MainEarthFamilyBitMap                     1000	//(Left Origin = 8, Top Origin = 25, Bitmap Resource ID = 1000, Usable = 1)
#define MainColorSquareGadget                     1001	//(Left Origin = 79, Top Origin = 18, Width = 80, Height = 80, Usable = 1)
#define MainColorDepthLabel                       1003	//(Left Origin = 2, Top Origin = 118, Usable = 1, Font = Bold)
#define MainBitmapLabel                           1011	//(Left Origin = 2, Top Origin = 89, Usable = 1, Font = Bold)
#define MainColorDepth1BitPushButton              1002	//(Left Origin = 6, Top Origin = 132, Width = 36, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define MainColorDepth2BitPushButton              1004	//(Left Origin = 43, Top Origin = 132, Width = 36, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define MainColorDepth4BitPushButton              1005	//(Left Origin = 80, Top Origin = 132, Width = 36, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define MainColorDepth8BitPushButton              1006	//(Left Origin = 117, Top Origin = 132, Width = 36, Height = 12, Usable = 1, Group ID = 1, Font = Standard)
#define MainBitmapFamilyPushButton                1009	//(Left Origin = 6, Top Origin = 103, Width = 73, Height = 12, Usable = 1, Group ID = 2, Font = Standard)
#define MainBitmapSinglePushButton                1010	//(Left Origin = 80, Top Origin = 103, Width = 73, Height = 12, Usable = 1, Group ID = 2, Font = Standard)
#define ColorTestFormGroupID                      0
#define ColorTestFormGroupID2                     1
#define ColorTestFormGroupID3                     2


//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1105	//(Left Origin = 58, Top Origin = 133, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutEmailLabel                           1101	//(Left Origin = 30, Top Origin = 64, Usable = 1, Font = Standard)
#define AboutTitleLabel                           1102	//(Left Origin = 49, Top Origin = 21, Usable = 1, Font = Large)
#define AboutCopyrightLabel                       1103	//(Left Origin = 30, Top Origin = 52, Usable = 1, Font = Standard)
#define AboutVersionLabel                         1104	//(Left Origin = 54, Top Origin = 37, Usable = 1, Font = Standard)
#define AboutBlurb1Label                          1106	//(Left Origin = 36, Top Origin = 83, Usable = 1, Font = Standard)
#define AboutBlurb2Label                          1107	//(Left Origin = 20, Top Origin = 95, Usable = 1, Font = Standard)
#define AboutBlurb3Label                          1108	//(Left Origin = 12, Top Origin = 107, Usable = 1, Font = Standard)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1000
#define UnsupportedDepthAlert                     1000
#define UnsupportedDepthOK                        0

//	Resource: MBAR 1000
#define MainFormMenuBar                           1000

//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAboutColorTest                 1000

//	Resource: PICT 1000
#define Earth8bppBitmap                           1000
//	Resource: PICT 1100
#define Earth4bppBitmap                           1100
//	Resource: PICT 1200
#define Earth2bppBitmap                           1200
//	Resource: PICT 1300
#define Earth1bppBitmap                           1300
//	Resource: tbmf 1000
#define EarthFamilyBitmapFamily                   1000

//	Resource: tbmf 2000
#define EarthSingleBitmapFamily                   2000
