//	Header generated by Constructor for Pilot 1.0.2
//
//	Generated at 7:03:14 PM on Thursday, October 07, 1999
//
//	Generated for file: T:\TRGProd\Nomad\sw\OS\Libs\CF\demo101\Src\Starter.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALMPILOT;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Pilot App Name: 		"Cf Demo"
//
//	Pilot App Version: 		"1.01"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainDoneButton                            1001	//(Left Origin = 59, Top Origin = 76, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1100
#define AbortRetryAlert                           1100
#define AbortRetryAbort                           0
#define AbortRetryRetry                           1

//	Resource: Talt 1200
#define AbortFormatAlert                          1200
#define AbortFormatAbort                          0
#define AbortFormatFormat                         1

//	Resource: Talt 1300
#define ClearAbortRetryAlert                      1300
#define ClearAbortRetryAbort                      0
#define ClearAbortRetryRetry                      1
#define ClearAbortRetryClear                      2

//	Resource: MBAR 1000
#define MainFormMenuBar                           1000

//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAboutStarterApp                1000
