//	Header generated by Constructor for Palm OS¨ 1.5
//
//	Generated at 6:52:01 PM on Thursday, November 11, 1999
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"SampleCalc"
//
//	Palm App Version: 		"1.0"



//	Resource: tFRM 1000
#define MainForm                                  1000
#define MainZeroButton                            1013
#define MainDecimalButton                         1014
#define MainAddButton                             1015
#define MainEnterButton                           1021
#define MainOneButton                             1022
#define MainTwoButton                             1023
#define MainThreeButton                           1024
#define MainSubButton                             1025
#define MainEXPButton                             1031
#define MainFourButton                            1032
#define MainFiveButton                            1033
#define MainSixButton                             1034
#define MainMulButton                             1035
#define MainCHSButton                             1041
#define MainSevenButton                           1042
#define MainEightButton                           1043
#define MainNineButton                            1044
#define MainDivButton                             1045
#define MainBackButton                            1051
#define MainExchgButton                           1052
#define MainUser1Button                           1053
#define MainUser2Button                           1054
#define MainUser3Button                           1055
#define MainUnnamed1001BitMap                     1001


//	Resource: tFRM 1100
#define AboutForm                                 1100
#define AboutOKButton                             1105
#define AboutTitleLabel                           1102
#define AboutText1Label                           1103
#define AboutText2Label                           1104


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: MBAR 1000
#define MainFormMenuBar                           1000

//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAboutSampleCalc                1000

//	Resource: PICT 1001
#define SampleCalcDisplayBitmap                   1001

