//	Header generated by Constructor for Pilot 1.0.2
//
//	Generated at 9:50:52 AM on Thursday, April 01, 1999
//
//	Generated for file: C:\Program Files\Metrowerks\CodeWarrior\SCANNER_SDK_1.31\Samples\Scandemo\Rsc\RESOURCE.FRK\ScanDemoRsc.rsr
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALMPILOT;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Pilot App Name: 		"Demo Scan"
//
//	Pilot App Version: 		"1.31"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 1000, Menu Bar ID = 1000, Default Button ID = 0)
#define MainSCANButton                            1004	//(Left Origin = 20, Top Origin = 147, Width = 40, Height = 12, Usable = 1, Anchor Left = 0, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainUPCButton                             1013	//(Left Origin = 16, Top Origin = 18, Width = 60, Height = 11, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainCODE128Button                         1014	//(Left Origin = 15, Top Origin = 32, Width = 60, Height = 11, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainCODE39Button                          1015	//(Left Origin = 15, Top Origin = 46, Width = 60, Height = 11, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainCODE93Button                          1016	//(Left Origin = 15, Top Origin = 60, Width = 60, Height = 11, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainCODABARButton                         1017	//(Left Origin = 93, Top Origin = 46, Width = 60, Height = 11, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainMSIButton                             1018	//(Left Origin = 93, Top Origin = 60, Width = 60, Height = 11, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainD2OF5Button                           1019	//(Left Origin = 92, Top Origin = 32, Width = 60, Height = 11, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainI2OF5Button                           1020	//(Left Origin = 94, Top Origin = 18, Width = 60, Height = 11, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainStopButton                            1029	//(Left Origin = 96, Top Origin = 147, Width = 40, Height = 12, Usable = 1, Anchor Left = 0, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainScanEnCheckbox                        1003	//(Left Origin = 1, Top Origin = 75, Width = 67, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define MainUPCEnCheckbox                         1021	//(Left Origin = 1, Top Origin = 17, Width = 12, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define MainCODE128EnCheckbox                     1022	//(Left Origin = 1, Top Origin = 31, Width = 12, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define MainCODE39EnCheckbox                      1023	//(Left Origin = 1, Top Origin = 45, Width = 12, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define MainCODE93EnCheckbox                      1024	//(Left Origin = 1, Top Origin = 58, Width = 12, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define MainI2OF5EnCheckbox                       1025	//(Left Origin = 79, Top Origin = 17, Width = 12, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define MainD2OF5EnCheckbox                       1026	//(Left Origin = 78, Top Origin = 31, Width = 12, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define MainCODABAREnCheckbox                     1027	//(Left Origin = 78, Top Origin = 45, Width = 12, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define MainMSIEnCheckbox                         1028	//(Left Origin = 78, Top Origin = 59, Width = 12, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define MainLEDCheckbox                           1030	//(Left Origin = 124, Top Origin = 75, Width = 36, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define MainScandataField                         1002	//(Left Origin = 54, Top Origin = 116, Width = 106, Height = 24, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainBarTypeField                          1009	//(Left Origin = 54, Top Origin = 103, Width = 106, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainTriggerModeLabelLabel                 1001	//(Left Origin = 3, Top Origin = 90, Usable = 1, Font = Bold)
#define MainBarTypeLabel                          1005	//(Left Origin = 3, Top Origin = 103, Usable = 1, Font = Bold)
#define MainBarDataLabel                          1006	//(Left Origin = 3, Top Origin = 116, Usable = 1, Font = Bold)
#define MainTriggerModeListList                   1010	//(Left Origin = 89, Top Origin = 90, Width = 40, Usable = 0, Font = Standard, Visible Items = 0)
#define MainTriggerModePopTriggerPopTrigger       1008	//(Left Origin = 89, Top Origin = 90, Width = 0, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1010)
#define SymbolScannerDemoFormGroupID              0


//	Resource: tFRM 1300
#define HardwareForm                              1300	//(Left Origin = 2, Top Origin = 8, Width = 156, Height = 150, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1300, Menu Bar ID = 0, Default Button ID = 0)
#define HardwareOKButton                          1310	//(Left Origin = 8, Top Origin = 134, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define HardwareCancelButton                      1311	//(Left Origin = 112, Top Origin = 134, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define HardwareRedundancyCheckbox                1301	//(Left Origin = 4, Top Origin = 33, Width = 70, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define HardwareBeepOnGoodDecodeCheckbox          1302	//(Left Origin = 4, Top Origin = 18, Width = 120, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define HardwareDecodeLEDOnTimeField              1304	//(Left Origin = 110, Top Origin = 79, Width = 20, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define HardwareAimDurationField                  1306	//(Left Origin = 82, Top Origin = 112, Width = 20, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define HardwareLaserOnTimeField                  1319	//(Left Origin = 82, Top Origin = 95, Width = 20, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define HardwareDecodeLedOnTimeLabel              1303	//(Left Origin = 4, Top Origin = 80, Usable = 1, Font = Bold)
#define HardwareAimDurationLabel                  1305	//(Left Origin = 4, Top Origin = 112, Usable = 1, Font = Bold)
#define HardwareLinearSecurityLabel               1307	//(Left Origin = 4, Top Origin = 48, Usable = 1, Font = Bold)
#define HardwareScanAngleLabel                    1312	//(Left Origin = 4, Top Origin = 64, Usable = 1, Font = Bold)
#define HardwareLaserOnTimeLabel                  1320	//(Left Origin = 4, Top Origin = 96, Usable = 1, Font = Bold)
#define HardwareLinearSecurityList                1308	//(Left Origin = 87, Top Origin = 48, Width = 65, Usable = 0, Font = Standard, Visible Items = 0)
#define HardwareScanAngleList                     1313	//(Left Origin = 63, Top Origin = 64, Width = 65, Usable = 0, Font = Standard, Visible Items = 0)
#define HardwareLinearSecurityPopTrigger          1309	//(Left Origin = 87, Top Origin = 48, Width = 0, Height = 13, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1308)
#define HardwareScanAnglePopTrigger               1314	//(Left Origin = 63, Top Origin = 64, Width = 0, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1313)
#define HardwareSetupFormGroupID                  0


//	Resource: tFRM 1600
#define UPCForm                                   1600	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1600, Menu Bar ID = 0, Default Button ID = 0)
#define UPCMoreButton                             1629	//(Left Origin = 27, Top Origin = 141, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define UPCCancelButton                           1630	//(Left Origin = 92, Top Origin = 141, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define UPCUPCEACheckbox                          1603	//(Left Origin = 16, Top Origin = 82, Width = 60, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define UPCUPCE1ACheckbox                         1604	//(Left Origin = 16, Top Origin = 94, Width = 60, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define UPCUPCACheckbox                           1605	//(Left Origin = 16, Top Origin = 30, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define UPCUPCECheckbox                           1606	//(Left Origin = 16, Top Origin = 42, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define UPCUPCE1Checkbox                          1607	//(Left Origin = 16, Top Origin = 54, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define UPCEAN8Checkbox                           1608	//(Left Origin = 87, Top Origin = 30, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define UPCEAN13Checkbox                          1609	//(Left Origin = 87, Top Origin = 42, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define UPCBooklandCheckbox                       1610	//(Left Origin = 87, Top Origin = 54, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define UPCEAN0ExtCheckbox                        1612	//(Left Origin = 15, Top Origin = 105, Width = 60, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define UPCEAN813Checkbox                         1613	//(Left Origin = 88, Top Origin = 82, Width = 60, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define UPCCouponCheckbox                         1614	//(Left Origin = 87, Top Origin = 94, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define UPCEnableBarcodesLabel                    1601	//(Left Origin = 4, Top Origin = 16, Usable = 1, Font = Bold)
#define UPCConversionsLabel                       1602	//(Left Origin = 4, Top Origin = 69, Usable = 1, Font = Bold)
#define UPCSecurityLevelLabel                     1615	//(Left Origin = 4, Top Origin = 122, Usable = 1, Font = Bold)
#define UPCSecurityLevelList                      1616	//(Left Origin = 82, Top Origin = 122, Width = 70, Usable = 0, Font = Standard, Visible Items = 0)
#define UPCSecurityLevelPopTrigger                1617	//(Left Origin = 82, Top Origin = 122, Width = 0, Height = 13, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1616)
#define UPCEANSetupFormGroupID                    0


//	Resource: tFRM 1700
#define UPCMoreForm                               1700	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1700, Menu Bar ID = 0, Default Button ID = 0)
#define UPCMoreOKButton                           1701	//(Left Origin = 28, Top Origin = 141, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define UPCMoreCancelButton                       1702	//(Left Origin = 92, Top Origin = 141, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define UPCMoreUPCACheckbox                       1707	//(Left Origin = 87, Top Origin = 16, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define UPCMoreUPCECheckbox                       1708	//(Left Origin = 87, Top Origin = 28, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define UPCMoreUPCE1Checkbox                      1709	//(Left Origin = 87, Top Origin = 41, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define UPCMoreRedundancyField                    1711	//(Left Origin = 72, Top Origin = 122, Width = 20, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 3, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define UPCMoreSupplementalsLabel                 1703	//(Left Origin = 4, Top Origin = 59, Usable = 1, Font = Bold)
#define UPCMoreTxCheckDigitLabel                  1706	//(Left Origin = 4, Top Origin = 16, Usable = 1, Font = Bold)
#define UPCMoreRedundancyLabel                    1710	//(Left Origin = 4, Top Origin = 122, Usable = 1, Font = Bold)
#define UPCMoreUPCAPreambleLabel                  1712	//(Left Origin = 4, Top Origin = 77, Usable = 1, Font = Bold)
#define UPCMoreUPCEPreambleLabel                  1715	//(Left Origin = 4, Top Origin = 91, Usable = 1, Font = Bold)
#define UPCMoreUPCE1PreambleLabel                 1718	//(Left Origin = 4, Top Origin = 106, Usable = 1, Font = Bold)
#define UPCMoreSupplementalsList                  1704	//(Left Origin = 95, Top Origin = 59, Width = 56, Usable = 0, Font = Standard, Visible Items = 0)
#define UPCMoreUPCAPreambleList                   1713	//(Left Origin = 95, Top Origin = 77, Width = 56, Usable = 0, Font = Standard, Visible Items = 0)
#define UPCMoreUPCEPreambleList                   1716	//(Left Origin = 95, Top Origin = 91, Width = 56, Usable = 0, Font = Standard, Visible Items = 0)
#define UPCMoreUPCE1PreambleList                  1719	//(Left Origin = 95, Top Origin = 105, Width = 56, Usable = 0, Font = Standard, Visible Items = 0)
#define UPCMoreSupplementalsPopTrigger            1705	//(Left Origin = 95, Top Origin = 59, Width = 0, Height = 13, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1704)
#define UPCMoreUPCAPreamblePopTrigger             1714	//(Left Origin = 95, Top Origin = 77, Width = 0, Height = 13, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1713)
#define UPCMoreUPCEPreamblePopTrigger             1717	//(Left Origin = 95, Top Origin = 91, Width = 0, Height = 13, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1716)
#define UPCMoreUPCE1PreamblePopTrigger            1720	//(Left Origin = 95, Top Origin = 105, Width = 0, Height = 13, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1719)
#define MoreUPCEANSetupFormGroupID                0


//	Resource: tFRM 1800
#define Code128Form                               1800	//(Left Origin = 2, Top Origin = 70, Width = 156, Height = 88, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1800, Menu Bar ID = 0, Default Button ID = 0)
#define Code128OKButton                           1805	//(Left Origin = 28, Top Origin = 73, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define Code128CancelButton                       1806	//(Left Origin = 92, Top Origin = 73, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define Code128Code128Checkbox                    1802	//(Left Origin = 40, Top Origin = 32, Width = 75, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define Code128UCCEAN128Checkbox                  1803	//(Left Origin = 39, Top Origin = 44, Width = 75, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define Code128ISBT128Checkbox                    1804	//(Left Origin = 39, Top Origin = 56, Width = 75, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define Code128EnableBarcodesLabel                1801	//(Left Origin = 4, Top Origin = 17, Usable = 1, Font = Bold)
#define Code128SetupFormGroupID                   0


//	Resource: tFRM 1900
#define Code39Form                                1900	//(Left Origin = 2, Top Origin = 21, Width = 156, Height = 137, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1900, Menu Bar ID = 0, Default Button ID = 0)
#define Code39CancelButton                        1915	//(Left Origin = 92, Top Origin = 122, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define Code39MoreButton                          1916	//(Left Origin = 28, Top Origin = 122, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define Code39Code39Checkbox                      1904	//(Left Origin = 9, Top Origin = 30, Width = 65, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define Code39Trioptic39Checkbox                  1905	//(Left Origin = 81, Top Origin = 30, Width = 65, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define Code39Convert39to32Checkbox               1906	//(Left Origin = 31, Top Origin = 48, Width = 95, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define Code39VerifyCheckDigitCheckbox            1907	//(Left Origin = 31, Top Origin = 62, Width = 95, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define Code39TxCheckDigitCheckbox                1908	//(Left Origin = 31, Top Origin = 76, Width = 95, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define Code39FullASCIICheckbox                   1909	//(Left Origin = 31, Top Origin = 90, Width = 95, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define Code39Code32PrefixCheckbox                1910	//(Left Origin = 31, Top Origin = 104, Width = 95, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define Code39EnableBarcodesLabel                 1903	//(Left Origin = 4, Top Origin = 16, Usable = 1, Font = Bold)
#define Code39SetupFormGroupID                    0


//	Resource: tFRM 2000
#define MoreCode39Form                            2000	//(Left Origin = 2, Top Origin = 72, Width = 156, Height = 86, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 2000, Menu Bar ID = 0, Default Button ID = 0)
#define MoreCode39OKButton                        2004	//(Left Origin = 28, Top Origin = 71, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MoreCode39CancelButton                    2005	//(Left Origin = 92, Top Origin = 71, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MoreCode39Length2Field                    2007	//(Left Origin = 57, Top Origin = 50, Width = 20, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define MoreCode39Length1Field                    2009	//(Left Origin = 57, Top Origin = 35, Width = 20, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define MoreCode39SetBCLengthsLabel               2001	//(Left Origin = 4, Top Origin = 20, Usable = 1, Font = Bold)
#define MoreCode39Length2Label                    2006	//(Left Origin = 6, Top Origin = 50, Usable = 1, Font = Bold)
#define MoreCode39Length1Label                    2008	//(Left Origin = 6, Top Origin = 35, Usable = 1, Font = Bold)
#define MoreCode39SetBCLengthsList                2002	//(Left Origin = 85, Top Origin = 20, Width = 60, Usable = 0, Font = Standard, Visible Items = 0)
#define MoreCode39SetBCLengthsPopTrigger          2003	//(Left Origin = 85, Top Origin = 20, Width = 0, Height = 13, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2002)


//	Resource: tFRM 2100
#define Code93Form                                2100	//(Left Origin = 2, Top Origin = 58, Width = 156, Height = 100, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 2100, Menu Bar ID = 0, Default Button ID = 0)
#define Code93OKButton                            2106	//(Left Origin = 28, Top Origin = 85, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define Code93CancelButton                        2107	//(Left Origin = 92, Top Origin = 85, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define Code93Code93Checkbox                      2102	//(Left Origin = 90, Top Origin = 16, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define Code93Length2Field                        2109	//(Left Origin = 57, Top Origin = 64, Width = 20, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define Code93Length1Field                        2111	//(Left Origin = 57, Top Origin = 49, Width = 20, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define Code93EnableBarcodesLabel                 2101	//(Left Origin = 4, Top Origin = 16, Usable = 1, Font = Bold)
#define Code93SetBCLengthsLabel                   2103	//(Left Origin = 4, Top Origin = 34, Usable = 1, Font = Bold)
#define Code93Length2Label                        2108	//(Left Origin = 6, Top Origin = 64, Usable = 1, Font = Bold)
#define Code93Length1Label                        2110	//(Left Origin = 6, Top Origin = 49, Usable = 1, Font = Bold)
#define Code93SetBCLengthsList                    2104	//(Left Origin = 85, Top Origin = 34, Width = 60, Usable = 0, Font = Standard, Visible Items = 0)
#define Code93SetBCLengthsPopTrigger              2105	//(Left Origin = 85, Top Origin = 34, Width = 0, Height = 13, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2104)
#define Code93SetupFormGroupID                    0


//	Resource: tFRM 2200
#define I2of5Form                                 2200	//(Left Origin = 2, Top Origin = 16, Width = 156, Height = 142, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 2200, Menu Bar ID = 0, Default Button ID = 0)
#define I2of5OKButton                             2204	//(Left Origin = 28, Top Origin = 127, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define I2of5CancelButton                         2205	//(Left Origin = 92, Top Origin = 127, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define I2of5I2of5Checkbox                        2211	//(Left Origin = 90, Top Origin = 16, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define I2of5ConverttoEAN13Checkbox               2212	//(Left Origin = 4, Top Origin = 32, Width = 120, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define I2of5TxCheckDigitCheckbox                 2214	//(Left Origin = 4, Top Origin = 46, Width = 120, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define I2of5Length2Field                         2207	//(Left Origin = 57, Top Origin = 106, Width = 20, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define I2of5Length1Field                         2209	//(Left Origin = 57, Top Origin = 92, Width = 20, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define I2of5SetBCLengthsLabel                    2201	//(Left Origin = 4, Top Origin = 78, Usable = 1, Font = Bold)
#define I2of5Length2Label                         2206	//(Left Origin = 6, Top Origin = 106, Usable = 1, Font = Bold)
#define I2of5Length1Label                         2208	//(Left Origin = 6, Top Origin = 92, Usable = 1, Font = Bold)
#define I2of5EnableBarcodesLabel                  2210	//(Left Origin = 4, Top Origin = 16, Usable = 1, Font = Bold)
#define I2of5VerifyCheckDigitLabel                2213	//(Left Origin = 3, Top Origin = 62, Usable = 1, Font = Bold)
#define I2of5SetBCLengthsList                     2202	//(Left Origin = 85, Top Origin = 78, Width = 60, Usable = 0, Font = Standard, Visible Items = 0)
#define I2of5VerifyCheckDigitList                 2215	//(Left Origin = 100, Top Origin = 62, Width = 50, Usable = 0, Font = Standard, Visible Items = 0)
#define I2of5SetBCLengthsPopTrigger               2203	//(Left Origin = 85, Top Origin = 78, Width = 0, Height = 13, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2202)
#define I2of5VerifyCheckDigitPopTrigger           2216	//(Left Origin = 100, Top Origin = 62, Width = 0, Height = 13, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2215)
#define Interleaved2of5SetupFormGroupID           0


//	Resource: tFRM 2300
#define D2of5Form                                 2300	//(Left Origin = 2, Top Origin = 58, Width = 156, Height = 100, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 2300, Menu Bar ID = 0, Default Button ID = 0)
#define D2of5OKButton                             2306	//(Left Origin = 28, Top Origin = 85, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define D2of5CancelButton                         2307	//(Left Origin = 92, Top Origin = 85, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define D2of5D2of5Checkbox                        2302	//(Left Origin = 90, Top Origin = 16, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define D2of5Length2Field                         2309	//(Left Origin = 57, Top Origin = 64, Width = 20, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define D2of5Length1Field                         2311	//(Left Origin = 57, Top Origin = 49, Width = 20, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define D2of5EnableBarcodesLabel                  2301	//(Left Origin = 4, Top Origin = 16, Usable = 1, Font = Bold)
#define D2of5SetBCLengthsLabel                    2303	//(Left Origin = 4, Top Origin = 34, Usable = 1, Font = Bold)
#define D2of5Length2Label                         2308	//(Left Origin = 6, Top Origin = 64, Usable = 1, Font = Bold)
#define D2of5Length1Label                         2310	//(Left Origin = 6, Top Origin = 49, Usable = 1, Font = Bold)
#define D2of5SetBCLengthsList                     2304	//(Left Origin = 85, Top Origin = 34, Width = 60, Usable = 0, Font = Standard, Visible Items = 0)
#define D2of5SetBCLengthsPopTrigger               2305	//(Left Origin = 85, Top Origin = 34, Width = 0, Height = 13, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2304)
#define D2of5SetupFormGroupID                     0


//	Resource: tFRM 2400
#define CodabarForm                               2400	//(Left Origin = 2, Top Origin = 30, Width = 156, Height = 128, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 2400, Menu Bar ID = 0, Default Button ID = 0)
#define CodabarOKButton                           2406	//(Left Origin = 28, Top Origin = 113, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define CodabarCancelButton                       2407	//(Left Origin = 92, Top Origin = 113, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define CodabarCodabarCheckbox                    2402	//(Left Origin = 90, Top Origin = 16, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define CodabarNOTISEditingCheckbox               2412	//(Left Origin = 4, Top Origin = 46, Width = 120, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define CodabarCLSIEditingCheckbox                2413	//(Left Origin = 4, Top Origin = 32, Width = 120, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define CodabarLength2Field                       2409	//(Left Origin = 57, Top Origin = 92, Width = 20, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define CodabarLength1Field                       2411	//(Left Origin = 57, Top Origin = 78, Width = 20, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define CodabarEnableBarcodesLabel                2401	//(Left Origin = 4, Top Origin = 16, Usable = 1, Font = Bold)
#define CodabarSetBCLengthsLabel                  2403	//(Left Origin = 4, Top Origin = 64, Usable = 1, Font = Bold)
#define CodabarLength2Label                       2408	//(Left Origin = 6, Top Origin = 92, Usable = 1, Font = Bold)
#define CodabarLength1Label                       2410	//(Left Origin = 6, Top Origin = 78, Usable = 1, Font = Bold)
#define CodabarSetBCLengthsList                   2404	//(Left Origin = 85, Top Origin = 64, Width = 60, Usable = 0, Font = Standard, Visible Items = 0)
#define CodabarSetBCLengthsPopTrigger             2405	//(Left Origin = 85, Top Origin = 64, Width = 0, Height = 13, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2404)
#define CodabarSetupFormGroupID                   0


//	Resource: tFRM 2500
#define MSIPlesseyForm                            2500	//(Left Origin = 2, Top Origin = 16, Width = 156, Height = 142, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 2500, Menu Bar ID = 0, Default Button ID = 0)
#define MSIPlesseyOKButton                        2504	//(Left Origin = 28, Top Origin = 127, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MSIPlesseyCancelButton                    2505	//(Left Origin = 92, Top Origin = 127, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MSIPlesseyMSIPlesseyCheckbox              2511	//(Left Origin = 89, Top Origin = 16, Width = 66, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define MSIPlesseyTxCheckDigitCheckbox            2514	//(Left Origin = 4, Top Origin = 32, Width = 120, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define MSIPlesseyLength2Field                    2507	//(Left Origin = 57, Top Origin = 106, Width = 20, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define MSIPlesseyLength1Field                    2509	//(Left Origin = 57, Top Origin = 92, Width = 20, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define MSIPlesseySetBCLengthsLabel               2501	//(Left Origin = 4, Top Origin = 78, Usable = 1, Font = Bold)
#define MSIPlesseyLength2Label                    2506	//(Left Origin = 6, Top Origin = 106, Usable = 1, Font = Bold)
#define MSIPlesseyLength1Label                    2508	//(Left Origin = 6, Top Origin = 92, Usable = 1, Font = Bold)
#define MSIPlesseyEnableBarcodesLabel             2510	//(Left Origin = 4, Top Origin = 16, Usable = 1, Font = Bold)
#define MSIPlesseyCheckDigitTypeLabel             2512	//(Left Origin = 4, Top Origin = 62, Usable = 1, Font = Bold)
#define MSIPlesseyCheckDigitsLabel                2513	//(Left Origin = 2, Top Origin = 48, Usable = 1, Font = Bold)
#define MSIPlesseySetBCLengthsList                2502	//(Left Origin = 85, Top Origin = 78, Width = 60, Usable = 0, Font = Standard, Visible Items = 0)
#define MSIPlesseyCheckDigitsList                 2515	//(Left Origin = 69, Top Origin = 48, Width = 60, Usable = 0, Font = Standard, Visible Items = 0)
#define MSIPlesseyCheckDigitTypeList              2517	//(Left Origin = 92, Top Origin = 62, Width = 60, Usable = 0, Font = Standard, Visible Items = 0)
#define MSIPlesseySetBCLengthsPopTrigger          2503	//(Left Origin = 85, Top Origin = 78, Width = 0, Height = 13, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2502)
#define MSIPlesseyCheckDigitsPopTrigger           2516	//(Left Origin = 69, Top Origin = 48, Width = 0, Height = 13, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2515)
#define MSIPlesseyCheckDigitTypePopTrigger        2518	//(Left Origin = 92, Top Origin = 62, Width = 0, Height = 13, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2517)
#define MSIPlesseySetupFormGroupID                0


//	Resource: tFRM 2600
#define CodeFormatForm                            2600	//(Left Origin = 2, Top Origin = 29, Width = 156, Height = 129, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 2600, Menu Bar ID = 0, Default Button ID = 2601)
#define CodeFormatOKButton                        2601	//(Left Origin = 28, Top Origin = 114, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define CodeFormatCancelButton                    2602	//(Left Origin = 92, Top Origin = 114, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define CodeFormatPrefixField                     2611	//(Left Origin = 76, Top Origin = 66, Width = 20, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define CodeFormatSuffix1Field                    2613	//(Left Origin = 76, Top Origin = 80, Width = 20, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define CodeFormatSuffix2Field                    2615	//(Left Origin = 76, Top Origin = 94, Width = 20, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define CodeFormatCodeIDCharLabel                 2603	//(Left Origin = 4, Top Origin = 20, Usable = 1, Font = Bold)
#define CodeFormatTxFormatLabel                   2606	//(Left Origin = 4, Top Origin = 34, Usable = 1, Font = Bold)
#define CodeFormatPrefixSuffixLabel               2609	//(Left Origin = 4, Top Origin = 52, Usable = 1, Font = Bold)
#define CodeFormatPrefixLabel                     2610	//(Left Origin = 8, Top Origin = 66, Usable = 1, Font = Bold)
#define CodeFormatSuffix1S1Label                  2612	//(Left Origin = 8, Top Origin = 80, Usable = 1, Font = Bold)
#define CodeFormatSuffix2S2Label                  2614	//(Left Origin = 8, Top Origin = 94, Usable = 1, Font = Bold)
#define CodeFormatCodeIDCharList                  2604	//(Left Origin = 71, Top Origin = 20, Width = 70, Usable = 0, Font = Standard, Visible Items = 0)
#define CodeFormatTxFormatList                    2607	//(Left Origin = 71, Top Origin = 34, Width = 70, Usable = 0, Font = Standard, Visible Items = 0)
#define CodeFormatCodeIDCharPopTrigger            2605	//(Left Origin = 71, Top Origin = 20, Width = 0, Height = 13, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2604)
#define CodeFormatTxFormatPopTrigger              2608	//(Left Origin = 71, Top Origin = 34, Width = 0, Height = 13, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2607)


//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1101	//(Left Origin = 60, Top Origin = 141, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutUnnamed1108BitMap                    1100	//(Left Origin = 4, Top Origin = 12, Bitmap Resource ID = 1100, Usable = 1)
#define AboutDecoderLabel                         1102	//(Left Origin = 4, Top Origin = 96, Usable = 1, Font = Standard)
#define AboutDecoderVerLabel                      1103	//(Left Origin = 73, Top Origin = 96, Usable = 1, Font = Standard)
#define AboutScanManagerLabel                     1104	//(Left Origin = 4, Top Origin = 110, Usable = 1, Font = Standard)
#define AboutScanMgrVerLabel                      1105	//(Left Origin = 95, Top Origin = 110, Usable = 1, Font = Standard)
#define AboutPortDriverLabel                      1106	//(Left Origin = 4, Top Origin = 124, Usable = 1, Font = Standard)
#define AboutScanDrvVerLabel                      1107	//(Left Origin = 85, Top Origin = 124, Usable = 1, Font = Standard)
#define AboutCopyrightLabel                       1109	//(Left Origin = 4, Top Origin = 68, Usable = 1, Font = Standard)
#define AboutCopyrighttooLabel                    1110	//(Left Origin = 4, Top Origin = 82, Usable = 1, Font = Standard)


//	Resource: tFRM 2800
#define BeepFrequenciesForm                       2800	//(Left Origin = 2, Top Origin = 61, Width = 156, Height = 97, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 2800, Menu Bar ID = 0, Default Button ID = 0)
#define BeepFrequenciesOKButton                   2813	//(Left Origin = 28, Top Origin = 82, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BeepFrequenciesCancelButton               2814	//(Left Origin = 92, Top Origin = 82, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BeepFrequenciesTestDecodeButton           2815	//(Left Origin = 97, Top Origin = 20, Width = 36, Height = 11, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BeepFrequenciesTestLowButton              2816	//(Left Origin = 97, Top Origin = 34, Width = 36, Height = 11, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BeepFrequenciesTestMedButton              2817	//(Left Origin = 97, Top Origin = 48, Width = 36, Height = 11, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BeepFrequenciesTestHighButton             2818	//(Left Origin = 97, Top Origin = 62, Width = 36, Height = 11, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BeepFrequenciesDecodeFreqField            2802	//(Left Origin = 46, Top Origin = 20, Width = 30, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 6, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define BeepFrequenciesLowFreqField               2804	//(Left Origin = 46, Top Origin = 34, Width = 30, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 6, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define BeepFrequenciesMedFreqField               2806	//(Left Origin = 46, Top Origin = 48, Width = 30, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 6, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define BeepFrequenciesHighFreqField              2808	//(Left Origin = 46, Top Origin = 62, Width = 30, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 6, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define BeepFrequenciesDecodeFreqLabel            2801	//(Left Origin = 4, Top Origin = 20, Usable = 1, Font = Bold)
#define BeepFrequenciesLowFreqLabel               2803	//(Left Origin = 19, Top Origin = 34, Usable = 1, Font = Bold)
#define BeepFrequenciesMedFreqLabel               2805	//(Left Origin = 18, Top Origin = 48, Usable = 1, Font = Bold)
#define BeepFrequenciesHighFreqLabel              2807	//(Left Origin = 17, Top Origin = 62, Usable = 1, Font = Bold)
#define BeepFrequenciesUnnamed2809Label           2809	//(Left Origin = 78, Top Origin = 20, Usable = 1, Font = Standard)
#define BeepFrequenciesUnnamed2810Label           2810	//(Left Origin = 78, Top Origin = 34, Usable = 1, Font = Standard)
#define BeepFrequenciesUnnamed2811Label           2811	//(Left Origin = 78, Top Origin = 48, Usable = 1, Font = Standard)
#define BeepFrequenciesUnnamed2812Label           2812	//(Left Origin = 78, Top Origin = 62, Usable = 1, Font = Standard)


//	Resource: tFRM 2900
#define BeepDurationsForm                         2900	//(Left Origin = 2, Top Origin = 61, Width = 156, Height = 97, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 2900, Menu Bar ID = 0, Default Button ID = 0)
#define BeepDurationsOKButton                     2913	//(Left Origin = 28, Top Origin = 82, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BeepDurationsCancelButton                 2914	//(Left Origin = 92, Top Origin = 82, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BeepDurationsTestDecodeButton             2915	//(Left Origin = 97, Top Origin = 20, Width = 36, Height = 11, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BeepDurationsTestShortButton              2916	//(Left Origin = 97, Top Origin = 34, Width = 36, Height = 11, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BeepDurationsTestMedButton                2917	//(Left Origin = 97, Top Origin = 48, Width = 36, Height = 11, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BeepDurationsTestLongButton               2918	//(Left Origin = 97, Top Origin = 62, Width = 36, Height = 11, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BeepDurationsDecodeDurField               2902	//(Left Origin = 46, Top Origin = 20, Width = 30, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 6, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define BeepDurationsShortDurField                2904	//(Left Origin = 46, Top Origin = 34, Width = 30, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 6, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define BeepDurationsMedDurField                  2906	//(Left Origin = 46, Top Origin = 48, Width = 30, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 6, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define BeepDurationsLongDurField                 2908	//(Left Origin = 46, Top Origin = 62, Width = 30, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 6, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define BeepDurationsDecodeDurLabel               2901	//(Left Origin = 4, Top Origin = 20, Usable = 1, Font = Bold)
#define BeepDurationsShortDurLabel                2903	//(Left Origin = 11, Top Origin = 34, Usable = 1, Font = Bold)
#define BeepDurationsMedDurLabel                  2905	//(Left Origin = 18, Top Origin = 48, Usable = 1, Font = Bold)
#define BeepDurationsLongDurLabel                 2907	//(Left Origin = 16, Top Origin = 62, Usable = 1, Font = Bold)
#define BeepDurationsUnnamed2909Label             2909	//(Left Origin = 78, Top Origin = 20, Usable = 1, Font = Standard)
#define BeepDurationsUnnamed2910Label             2910	//(Left Origin = 78, Top Origin = 34, Usable = 1, Font = Standard)
#define BeepDurationsUnnamed2911Label             2911	//(Left Origin = 78, Top Origin = 48, Usable = 1, Font = Standard)
#define BeepDurationsUnnamed2912Label             2912	//(Left Origin = 78, Top Origin = 62, Usable = 1, Font = Standard)


//	Resource: tFRM 3000
#define DecoderForm                               3000	//(Left Origin = 2, Top Origin = 77, Width = 156, Height = 81, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 3000, Menu Bar ID = 0, Default Button ID = 0)
#define DecoderOKButton                           3010	//(Left Origin = 28, Top Origin = 66, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DecoderCancelButton                       3011	//(Left Origin = 92, Top Origin = 66, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DecoderInterCharDelayField                3002	//(Left Origin = 90, Top Origin = 20, Width = 20, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define DecoderRespTimeoutField                   3005	//(Left Origin = 90, Top Origin = 34, Width = 20, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define DecoderCharTimeoutField                   3008	//(Left Origin = 90, Top Origin = 48, Width = 20, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 2, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define DecoderInterCharDelayLabel                3001	//(Left Origin = 4, Top Origin = 20, Usable = 1, Font = Bold)
#define DecoderUnnamed3003Label                   3003	//(Left Origin = 111, Top Origin = 20, Usable = 1, Font = Standard)
#define DecoderRespTimeoutLabel                   3004	//(Left Origin = 15, Top Origin = 34, Usable = 1, Font = Bold)
#define DecoderUnnamed3006Label                   3006	//(Left Origin = 111, Top Origin = 34, Usable = 1, Font = Standard)
#define DecoderCharTimeoutLabel                   3007	//(Left Origin = 17, Top Origin = 48, Usable = 1, Font = Bold)
#define DecoderUnnamed3009Label                   3009	//(Left Origin = 111, Top Origin = 48, Usable = 1, Font = Standard)


//	Resource: tFRM 3100
#define BeepTestForm                              3100	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define BeepTestBeepButton                        3102	//(Left Origin = 27, Top Origin = 138, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BeepTestCancelButton                      3103	//(Left Origin = 89, Top Origin = 138, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define BeepTestBeepTypeList                      3101	//(Left Origin = 27, Top Origin = 17, Width = 100, Usable = 1, Font = Standard, Visible Items = 10)


//	Resource: Talt 1000
#define BatteryErrorAlert                         1000
#define BatteryErrorOK                            0

//	Resource: Talt 1100
#define WrongHardwareAlert                        1100
#define WrongHardwareOK                           0

//	Resource: Talt 1200
#define OpenFailedAlert                           1200
#define OpenFailedOK                              0

//	Resource: MBAR 1000
#define MainMenuBar                               1000

//	Resource: MENU 1000
#define OptionsMenu                               1000
#define OptionsResetDefaults                      1000	// Command Key: R
#define OptionsAbout                              1002	// Command Key: A

//	Resource: MENU 1100
#define SetupMenu                                 1100
#define SetupHardware                             1100	// Command Key: H
#define SetupCodeFormat                           1101	// Command Key: T

//	Resource: MENU 1200
#define BeepMenu                                  1200
#define BeepFrequency                             1200	// Command Key: F
#define BeepDuration                              1201	// Command Key: N
#define BeepPatterns                              1202	// Command Key: P

//	Resource: tSTR 1000
#define MainFormHelpString                        1000	// "Test and Control of SE 1223 Scanner using SSI. Configure SE 1223 as follows to operate correctly.  This may be done using Parameter Barcodes.   1. Set All Defaults Parameter 2. Triggering Mode = HOST 3. Send Packeted Decode Data"

//	Resource: tSTR 1200
#define PreferencesFormHelpString                 1200	// ""

//	Resource: tSTR 1300
#define HardwareFormHelpString                    1300	// ""

//	Resource: tSTR 1700
#define UPCMoreFormHelpString                     1700	// ""

//	Resource: tSTR 1800
#define Code128FormHelpString                     1800	// ""

//	Resource: tSTR 1900
#define Code39FormHelpString                      1900	// ""

//	Resource: tSTR 2000
#define MoreCode39FormHelpString                  2000	// ""

//	Resource: tSTR 2100
#define Code93FormHelpString                      2100	// ""

//	Resource: tSTR 2200
#define I2of5FormHelpString                       2200	// ""

//	Resource: tSTR 2300
#define D2of5FormHelpString                       2300	// ""

//	Resource: tSTR 2400
#define CodabarFormHelpString                     2400	// ""

//	Resource: tSTR 2500
#define MSIPlesseyFormHelpString                  2500	// ""

//	Resource: tSTR 2600
#define CodeFormatFormHelpString                  2600	// ""

//	Resource: tSTR 1600
#define UPCFormHelpString                         1600	// ""

//	Resource: tSTR 1500
#define TriggerFormHelpString                     1500	// ""

//	Resource: tSTR 2800
#define BeepFrequencySettingFormHelpString        2800	// ""

//	Resource: tSTR 2900
#define BeepDurationSettingsFormHelpString        2900	// ""

//	Resource: tSTR 3000
#define DecoderSettingsFormHelpString             3000	// ""

//	Resource: tSTR 3100
#define BCTypeNotApplicableString                 3100	// "Not Applicable"

//	Resource: tSTR 3200
#define BCTypeCode39String                        3200	// "Code 39"

//	Resource: tSTR 3300
#define BCTypeCodabarString                       3300	// "Codabar"

//	Resource: tSTR 3400
#define BCTypeCode128String                       3400	// "Code 128"

//	Resource: tSTR 3500
#define BCTypeDiscrete2Of5String                  3500	// "Discrete 2 of 5"

//	Resource: tSTR 3600
#define BCTypeIATA2of5String                      3600	// "IATA 2 of 5"

//	Resource: tSTR 3700
#define BCTypeInterleaved2Of5String               3700	// "Interleaved 2 of 5"

//	Resource: tSTR 3800
#define BCTypeCode93String                        3800	// "Code 93"

//	Resource: tSTR 3900
#define BCTypeUPCAString                          3900	// "UPC A"

//	Resource: tSTR 4000
#define BCTypeUPCA2SuppsString                    4000	// "UPC A with 2 Supps."

//	Resource: tSTR 4100
#define BCTypeUPCA5SuppsString                    4100	// "UPC A with 5 Supps."

//	Resource: tSTR 4200
#define BCTypeUPCEOString                         4200	// "UPC EO"

//	Resource: tSTR 4300
#define BCTypeUPCEO2SuppsString                   4300	// "UPC EO with 2 Supps."

//	Resource: tSTR 4400
#define BCTypeUPCEO5SuppsString                   4400	// "UPC EO with 5 Supps."

//	Resource: tSTR 4500
#define BCTypeEAN8String                          4500	// "EAN 8"

//	Resource: tSTR 4600
#define BCTypeEAN82SuppsString                    4600	// "EAN 8 with 2 Supps."

//	Resource: tSTR 4700
#define BCTypeEAN85SuppsString                    4700	// "EAN 8 with 5 Supps."

//	Resource: tSTR 4800
#define BCTypeEAN13String                         4800	// "EAN 13"

//	Resource: tSTR 4900
#define BCTypeEAN132SuppsString                   4900	// "EAN 13 with 2 Supps."

//	Resource: tSTR 5000
#define BCTypeEAN135SuppsString                   5000	// "EAN 13 with 5 Supps."

//	Resource: tSTR 5100
#define BCTypeMSIPlesseyString                    5100	// "MSI Plessey"

//	Resource: tSTR 5200
#define BCTypeEAN128String                        5200	// "EAN 128"

//	Resource: tSTR 5300
#define BCTypeUPCE1String                         5300	// "UPC E1"

//	Resource: tSTR 5400
#define BCTypeUPCE12SuppsString                   5400	// "UPC E1 with 2 Supps."

//	Resource: tSTR 5500
#define BCTypeUPCE15SuppsString                   5500	// "UPC E1 with 5 Supps."

//	Resource: tSTR 5600
#define BCTypeTriopticCode39String                5600	// "Trioptic Code 39"

//	Resource: tSTR 5700
#define BCTypeBooklandEANString                   5700	// "Bookland EAN"

//	Resource: tSTR 5800
#define BCTypeCouponCodeString                    5800	// "Coupon Code"

//	Resource: tSTL 1000
#define BarTypesStringList                        1000
//	Resource: PICT 1100
#define AboutScanManagerBitmap                    1100