/***********************************************************************
 *
 * Copyright (c) 1999, TRG, All Rights Reserved
 *
 * PROJECT:         Nomad FAT demo
 *
 * FILE:        cmm.h    
 *
 * DESCRIPTION:   Prototypes for cmd.c
 *
 * AUTHOR: Trevor Meyer         
 *
 * DATE: 8/9/99           
 *
 **********************************************************************/
#ifndef _CMD_H_
#define _CMD_H_

void CMDInit(void);
void CMDProcess(char chr);

#endif
