//	Header generated by Constructor for Pilot 1.0.2
//
//	Generated at 5:42:11 PM on Tuesday, January 25, 2000
//
//	Generated for file: T:\TRGProd\Nomad\sw\OS\Libs\Audio\Demo's\DTMF Example\cw\Src\Starter.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALMPILOT;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Pilot App Name: 		"DTMF Example"
//
//	Pilot App Version: 		"1.0"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainPlayItButton                          1001	//(Left Origin = 102, Top Origin = 133, Width = 51, Height = 13, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainDTMFStrField                          1003	//(Left Origin = 70, Top Origin = 30, Width = 85, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainUnnamed1002Label                      1002	//(Left Origin = 15, Top Origin = 31, Usable = 1, Font = Standard)


//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutAboutOKButton                        1101	//(Left Origin = 7, Top Origin = 145, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutUnnamed1102BitMap                    1000	//(Left Origin = 32, Top Origin = 17, Bitmap Resource ID = 1000, Usable = 1)
#define AboutUnnamed1103Label                     1103	//(Left Origin = 5, Top Origin = 94, Usable = 1, Font = Standard)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1000
#define CantOpenLibAlert                          1000
#define CantOpenLibOK                             0

//	Resource: Talt 1100
#define NeedAudioLibAlert                         1100
#define NeedAudioLibOK                            0

//	Resource: MBAR 1000
#define MainFormMenuBar                           1000

//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAboutDTMFExample               1000

//	Resource: PICT 1000
#define TRGLogoBitmap                             1000