//	Header generated by Constructor for Palm OS¨ 1.5
//
//	Generated at 2:49:57 PM on Thursday, November 18, 1999
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"PalmFinger"
//
//	Palm App Version: 		"3.0"



//	Resource: tFRM 1000
#define FingerForm                                1000
#define FingerFingerButton                        1001
#define FingerDisconnectButton                    1002
#define FingerAddressField                        1004
#define FingerResultField                         1005
#define FingerRetrievedField                      1010
#define FingerNetActivityGadget                   1009
#define FingerUnnamed1011GrafittiShift            1011
#define FingerUnnamed1003Label                    1003
#define FingerUnnamed1007Label                    1007
#define FingerResultScrollBar                     1006


//	Resource: Talt 128
#define PrintfAlert                               128
#define PrintfOk                                  0

//	Resource: Talt 129
#define ErrorNoticeAlert                          129
#define ErrorNoticeOk                             0

//	Resource: Talt 228
#define RomIncompatibleAlert                      228
#define RomIncompatibleOk                         0

//	Resource: tSTR 128
#define BadAddressString                          128
//	Resource: tSTR 129
#define TestAddr1String                           129
//	Resource: tSTR 130
#define TestAddr2String                           130
//	Resource: tSTR 131
#define TestAddr3String                           131
//	Resource: tSTR 132
#define WhoWriteErrorString                       132
//	Resource: tSTR 133
#define CouldNotOpenConnErrorString               133
//	Resource: tSTR 134
#define ObscureErrorString                        134
//	Resource: tSTR 135
#define OutOfMemErrorString                       135
//	Resource: tSTR 136
#define BadSetupErrorString                       136
//	Resource: tSTR 228
#define OpenConnString                            228
//	Resource: tSTR 328
#define AllocRxBufString                          328
//	Resource: tSTR 428
#define AllocDBMemString                          428
//	Resource: tSTR 528
#define NetReadErrorString                        528
//	Resource: tSTR 1000
#define NetRefreshErrorString                     1000
//	Resource: tSTR 1100
#define NetNotAvailErrorString                    1100
//	Resource: tSTR 1200
#define DBNotFoundOrDelString                     1200
//	Resource: tSTR 1300
#define DBNotCreatedString                        1300
//	Resource: PICT 1100
#define NetPulse0Bitmap                           1100
//	Resource: PICT 1101
#define NetPulse1Bitmap                           1101
//	Resource: PICT 1102
#define NetPulse2Bitmap                           1102
//	Resource: PICT 1103
#define NetPulse3Bitmap                           1103
//	Resource: PICT 1104
#define NetPulse4Bitmap                           1104

