//	Header generated by Constructor for Pilot 1.0.2
//
//	Generated at 4:39:42 PM on Thursday, June 24, 1999
//
//	Generated for file: C:\Program Files\Metrowerks\CodeWarrior\pt_062299\Print Sample\Src\Resource.frk\Print Sample.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALMPILOT;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Pilot App Name: 		"ptSample"
//
//	Pilot App Version: 		"1.1"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainONeilCheckbox                         1001	//(Left Origin = 76, Top Origin = 85, Width = 82, Height = 13, Usable = 1, Selected = 0, Group ID = 0, Font = Bold)
#define MainComtecCheckbox                        1002	//(Left Origin = 76, Top Origin = 61, Width = 55, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Bold)
#define MainPCLCheckbox                           1003	//(Left Origin = 76, Top Origin = 109, Width = 55, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Bold)
#define MainSerialCheckbox                        1004	//(Left Origin = 5, Top Origin = 61, Width = 60, Height = 13, Usable = 1, Selected = 0, Group ID = 0, Font = Bold)
#define Main9490Checkbox                          1005	//(Left Origin = 76, Top Origin = 97, Width = 55, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Bold)
#define MainIrCheckbox                            1007	//(Left Origin = 5, Top Origin = 73, Width = 60, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Bold)
#define MainEltronCheckbox                        1009	//(Left Origin = 76, Top Origin = 73, Width = 82, Height = 13, Usable = 1, Selected = 0, Group ID = 0, Font = Bold)
#define MainPostscriptCheckbox                    1010	//(Left Origin = 76, Top Origin = 121, Width = 80, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Bold)
#define MainTransportLabel                        1006	//(Left Origin = 9, Top Origin = 47, Usable = 1, Font = Bold)
#define MainPrinterLabel                          1008	//(Left Origin = 92, Top Origin = 47, Usable = 1, Font = Bold)
#define MainStatusLabel                           1013	//(Left Origin = 5, Top Origin = 34, Usable = 1, Font = Standard)
#define MainCommandList                           1015	//(Left Origin = 5, Top Origin = 55, Width = 66, Usable = 0, Font = Standard, Visible Items = 9)
#define MainPrintcapList                          1016	//(Left Origin = 76, Top Origin = 88, Width = 66, Usable = 0, Font = Standard, Visible Items = 6)
#define MainPrintCapPopTrigger                    1011	//(Left Origin = 77, Top Origin = 143, Width = 0, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1016)
#define MainCommandPopTrigger                     1014	//(Left Origin = 5, Top Origin = 143, Width = 0, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1015)
#define SymbolPrintSampleFormGroupID              0


//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 13, Width = 156, Height = 140, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOkButton                             1102	//(Left Origin = 56, Top Origin = 119, Width = 38, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutUnnamed1101Label                     1101	//(Left Origin = 9, Top Origin = 45, Usable = 1, Font = Standard)
#define AboutUnnamed1103Label                     1103	//(Left Origin = 10, Top Origin = 22, Usable = 1, Font = Bold)


//	Resource: tFRM 1200
#define InfoForm                                  1200	//(Left Origin = 2, Top Origin = 20, Width = 156, Height = 132, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 1200, Default Button ID = 2303)
#define InfoOkButton                              1203	//(Left Origin = 12, Top Origin = 114, Width = 37, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define InfoLabelField                            1201	//(Left Origin = 8, Top Origin = 17, Width = 134, Height = 22, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 30, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define InfoInfoField                             1202	//(Left Origin = 8, Top Origin = 44, Width = 134, Height = 60, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 128, Font = Standard, Auto Shift = 1, Has Scroll Bar = 1, Numeric = 0)
#define InfoInfoScrollBar                         1205	//(Left Origin = 145, Top Origin = 44, Width = 8, Height = 60, Usable = 1, Value = 0, Minimum Value = 0, Maximum Value = 0, Page Size = 0)


//	Resource: Talt 1400
#define NoPrinterSelectedAlert                    1400
#define NoPrinterSelectedOK                       0

//	Resource: Talt 1500
#define NoTransportSelectedAlert                  1500
#define NoTransportSelectedOK                     0

//	Resource: Talt 1600
#define OpenFailedAlert                           1600
#define OpenFailedOK                              0

//	Resource: Talt 1700
#define PrinterNotOpenAlert                       1700
#define PrinterNotOpenOK                          0

//	Resource: Talt 1800
#define PrinterOpenAlert                          1800
#define PrinterOpenOK                             0

//	Resource: Talt 1900
#define PrintStatusNoDataAlert                    1900
#define PrintStatusNoDataOK                       0

//	Resource: Talt 2000
#define PrinterTansportNotSupportedAlert          2000
#define PrinterTansportNotSupportedOK             0

//	Resource: MBAR 1000
#define MainFormMenuBar                           1000

//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAboutSymbolPrintSample         1000
