//	Header generated by Constructor for Palm OSª 1.2

//

//	Generated at 6:45:19 PM on Tuesday, October 26, 1999

//

//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OSª;

//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST

//

//	Palm App Name: 		"Beamer"

//

//	Palm App Version: 		"1.2"







//	Resource: tFRM 1000

#define BeamerMainForm                            1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)

#define BeamerMainClearButton                     1002	//(Left Origin = 78, Top Origin = 144, Width = 34, Height = 13, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)

#define BeamerMainSendButton                      1003	//(Left Origin = 119, Top Origin = 144, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)

#define BeamerMainPenPushButton                   1001	//(Left Origin = 8, Top Origin = 144, Width = 12, Height = 12, Usable = 0, Group ID = 1, Font = Standard)

#define BeamerMainErasePushButton                 1004	//(Left Origin = 21, Top Origin = 144, Width = 12, Height = 12, Usable = 0, Group ID = 1, Font = Standard)

#define BeamerFormGroupID                         1





//	Resource: Talt 1000

#define AskAlert                                  1000

#define AskYes                                    0

#define AskNo                                     1



//	Resource: Talt 1001

#define RomIncompatibleAlert                      1001

#define RomIncompatibleOK                         0



//	Resource: Talt 1100

#define InfoAlert                                 1100

#define InfoOK                                    0



//	Resource: MBAR 1000

#define MainMenuBar                               1000



//	Resource: MENU 1001

#define OptionsMenu                               1001

#define OptionsGetInfo                            1001	//  Command Key: i

#define OptionsBeamMe                             1002



//	Resource: tSTR 1000

#define HelpString                                1000	// "Beamer lets you beam a simple drawing to another device. Press the Beam button to send the beam, press the Clear button to erase everything. Use "Beam Me" in the menu to send this program to someone else!"


