//	Header generated by Constructor for Pilot 1.0.2
//
//	Generated at 1:49:45 PM on Thursday, April 08, 1999
//
//	Generated for file: D:\CodeWarrior5\Symbol NDK Support\Samples\Client\Echo\Src\Echo.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALMPILOT;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Pilot App Name: 		"Echo"
//
//	Pilot App Version: 		"1.0"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainStartButton                           1011	//(Left Origin = 30, Top Origin = 144, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainStopButton                            1012	//(Left Origin = 80, Top Origin = 144, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainModeCheckbox                          1001	//(Left Origin = 50, Top Origin = 128, Width = 55, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Bold)
#define MainHostIPField                           1003	//(Left Origin = 44, Top Origin = 38, Width = 103, Height = 11, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainSizeField                             1008	//(Left Origin = 44, Top Origin = 56, Width = 54, Height = 11, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainDelayField                            1009	//(Left Origin = 44, Top Origin = 76, Width = 54, Height = 11, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainStatusField                           1010	//(Left Origin = 43, Top Origin = 19, Width = 103, Height = 11, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainCountField                            1013	//(Left Origin = 44, Top Origin = 93, Width = 54, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 80, Font = Bold, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainTimeField                             1014	//(Left Origin = 8, Top Origin = 111, Width = 139, Height = 13, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainUnnamed1002Label                      1002	//(Left Origin = 8, Top Origin = 95, Usable = 1, Font = Bold)
#define MainUnnamed1004Label                      1004	//(Left Origin = 3, Top Origin = 39, Usable = 1, Font = Bold)
#define MainUnnamed1005Label                      1005	//(Left Origin = 20, Top Origin = 56, Usable = 1, Font = Bold)
#define MainUnnamed1006Label                      1006	//(Left Origin = 11, Top Origin = 76, Usable = 1, Font = Bold)
#define MainUnnamed1007Label                      1007	//(Left Origin = 4, Top Origin = 20, Usable = 1, Font = Bold)
#define Spectrum24Echov100FormGroupID             0


//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1101	//(Left Origin = 60, Top Origin = 141, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutSymbolLogoBitMap                     1100	//(Left Origin = 1, Top Origin = 13, Bitmap Resource ID = 1100, Usable = 1)
#define AboutDecoderField                         1103	//(Left Origin = 78, Top Origin = 96, Width = 75, Height = 13, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define AboutScanManagerField                     1105	//(Left Origin = 100, Top Origin = 111, Width = 53, Height = 13, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define AboutPortDriverField                      1107	//(Left Origin = 90, Top Origin = 124, Width = 63, Height = 13, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define AboutDecoderLabel                         1102	//(Left Origin = 4, Top Origin = 96, Usable = 1, Font = Standard)
#define AboutScanManagerLabel                     1104	//(Left Origin = 4, Top Origin = 110, Usable = 1, Font = Standard)
#define AboutPortDriverLabel                      1106	//(Left Origin = 4, Top Origin = 124, Usable = 1, Font = Standard)
#define AboutCopyrightLabel                       1109	//(Left Origin = 4, Top Origin = 68, Usable = 1, Font = Standard)
#define AboutCopyrighttooLabel                    1110	//(Left Origin = 4, Top Origin = 82, Usable = 1, Font = Standard)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1101
#define ConnectAlert                              1101
#define ConnectOK                                 0

//	Resource: Talt 1201
#define GeneralAlert                              1201
#define GeneralOK                                 0

//	Resource: MBAR 1000
#define MainFormMenuBar                           1000

//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAbout                          1000

//	Resource: PICT 1100
#define SymbolLogoBitmap                          1100