//	Header generated by Constructor for Pilot 1.0.2
//
//	Generated at 3:26:43 PM on Monday, 23 August, 1999
//
//	Generated for file: D:\Bible\code\ch04\cw\hello.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALMPILOT;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Pilot App Name: 		"Hello"
//
//	Pilot App Version: 		"1.0"



//	Resource: tFRM 1000
#define MainForm                                  1000
#define MainHelloButton                           1002
#define MainGoodbyeButton                         1003
#define MainNameField                             1001
#define MainUnnamed1099Label                      1099


//	Resource: Talt 1000
#define HelloAlert                                1000
#define HelloOK                                   0

//	Resource: Talt 1100
#define GoodbyeAlert                              1100
#define GoodbyeOK                                 0

//	Resource: Talt 1200
#define AboutAlert                                1200
#define AboutOK                                   0

//	Resource: MBAR 1000
#define MainMenuBar                               1000

//	Resource: MENU 1000
#define MainEditMenu                              1000
#define MainEditUndo                              1000
#define MainEditCut                               1001
#define MainEditCopy                              1002
#define MainEditPaste                             1003
#define MainEditSelectAll                         1004
#define MainEditKeyboard                          1006
#define MainEditGraffitiHelp                      1007

//	Resource: MENU 1100
#define MainOptionsMenu                           1100
#define MainOptionsAboutHelloWorld                1100
