//	Header generated by Constructor for Pilot 1.0.2
//
//	Generated at 9:42:29 AM on Wednesday, February 24, 1999
//
//	Generated for file: C:\sswork\palm\Apex sample\Src\Resource.frk\msr_sample.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALMPILOT;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Pilot App Name: 		"Apex MSR"
//
//	Pilot App Version: 		"1.0"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainNewButton                             1002	//(Left Origin = 62, Top Origin = 140, Width = 45, Height = 19, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainCardInfoField                         1001	//(Left Origin = 3, Top Origin = 17, Width = 154, Height = 130, Usable = 1, Editable = 0, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 300, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)


//	Resource: tFRM 1100
#define MSRInfoForm                               1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 155, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define MSRInfoOKButton                           1104	//(Left Origin = 62, Top Origin = 125, Width = 37, Height = 17, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MSRInfoCompanylogBitMap                   1100	//(Left Origin = 55, Top Origin = 20, Bitmap Resource ID = 1100, Usable = 1)
#define MSRInfoMSRLabel                           1101	//(Left Origin = 47, Top Origin = 70, Usable = 1, Font = Standard)
#define MSRInfoVersionLabel                       1102	//(Left Origin = 58, Top Origin = 85, Usable = 1, Font = Standard)


//	Resource: tFRM 1200
#define NoMSRForm                                 1200	//(Left Origin = 2, Top Origin = 5, Width = 154, Height = 135, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define NoMSROKButton                             1204	//(Left Origin = 58, Top Origin = 99, Width = 37, Height = 17, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define NoMSRWarningInfoLabel                     1201	//(Left Origin = 18, Top Origin = 31, Usable = 1, Font = Standard)
#define NoMSRCheckInfoLabel                       1203	//(Left Origin = 18, Top Origin = 51, Usable = 1, Font = Standard)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: PICT 1100
#define CreatedforBitmapResourceIDBitmap          1100