//	Header generated by Constructor for Palm OS¨ 1.5
//
//	Generated at 11:41:12 PM on Wednesday, July 26, 2000
//
//	Generated for file: C:\Bible\code\ch15\serialchat\cw\Rsc\serialchat.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"Serial Chat"
//
//	Palm App Version: 		"1.0"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainClearButton                           1006	//(Left Origin = 1, Top Origin = 147, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainIncomingField                         1001	//(Left Origin = 0, Top Origin = 28, Width = 153, Height = 48, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 255, Font = Standard, Auto Shift = 0, Has Scroll Bar = 1, Numeric = 0)
#define MainOutgoingField                         1002	//(Left Origin = 0, Top Origin = 94, Width = 153, Height = 48, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 255, Font = Standard, Auto Shift = 0, Has Scroll Bar = 1, Numeric = 0)
#define MainIncomingLabel                         1007	//(Left Origin = 0, Top Origin = 16, Usable = 1, Font = Bold)
#define MainOutgoingLabel                         1008	//(Left Origin = 0, Top Origin = 82, Usable = 1, Font = Bold)
#define MainIncomingScrollBar                     1003	//(Left Origin = 153, Top Origin = 28, Width = 7, Height = 48, Usable = 1, Value = 0, Minimum Value = 0, Maximum Value = 0, Page Size = 0)
#define MainOutgoingScrollBar                     1004	//(Left Origin = 153, Top Origin = 94, Width = 7, Height = 48, Usable = 1, Value = 0, Minimum Value = 0, Maximum Value = 0, Page Size = 0)


//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1105	//(Left Origin = 58, Top Origin = 133, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutEmailLabel                           1101	//(Left Origin = 30, Top Origin = 64, Usable = 1, Font = Standard)
#define AboutTitleLabel                           1102	//(Left Origin = 51, Top Origin = 21, Usable = 1, Font = Large)
#define AboutCopyrightLabel                       1103	//(Left Origin = 30, Top Origin = 52, Usable = 1, Font = Standard)
#define AboutVersionLabel                         1104	//(Left Origin = 56, Top Origin = 37, Usable = 1, Font = Standard)
#define AboutBlurb1Label                          1106	//(Left Origin = 36, Top Origin = 83, Usable = 1, Font = Standard)
#define AboutBlurb2Label                          1107	//(Left Origin = 12, Top Origin = 95, Usable = 1, Font = Standard)
#define AboutBlurb3Label                          1108	//(Left Origin = 12, Top Origin = 107, Usable = 1, Font = Standard)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1100
#define SerialOpenAlert                           1100
#define SerialOpenOK                              0

//	Resource: Talt 1200
#define SerialCheckAlert                          1200
#define SerialCheckOK                             0

//	Resource: Talt 1000
#define SerialSendAlert                           1000
#define SerialSendOK                              0

//	Resource: Talt 1300
#define SerialBusyAlert                           1300
#define SerialBusyOK                              0

//	Resource: Talt 1400
#define SerialTimeoutAlert                        1400
#define SerialTimeoutOK                           0

//	Resource: Talt 1500
#define NoNewSerialAlert                          1500
#define NoNewSerialOK                             0

//	Resource: MBAR 1000
#define MainMenuBar                               1000

//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAboutSerialChat                1000

//	Resource: MENU 1100
#define EditMenu                                  1100
#define EditUndo                                  1100	//  Command Key: U
#define EditCut                                   1101	//  Command Key: X
#define EditCopy                                  1102	//  Command Key: C
#define EditPaste                                 1103	//  Command Key: P
#define EditSelectAll                             1104	//  Command Key: S
#define EditKeyboard                              1106	//  Command Key: K
#define EditGraffitiHelp                          1107	//  Command Key: G
