//	Header generated by Constructor for Palm OS¨ 1.5
//
//	Generated at 6:46:00 PM on Thursday, November 11, 1999
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"DotDotTwo"
//
//	Palm App Version: 		"1.0"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 1005)
#define MainUnnamed1005Button                     1005	//(Left Origin = 56, Top Origin = 94, Width = 50, Height = 20, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define MainUnnamed1001BitMap                     1000	//(Left Origin = 15, Top Origin = 10, Bitmap Resource ID = 1000, Usable = 1)
#define MainUnnamed1006BitMap                     1001	//(Left Origin = 52, Top Origin = 126, Bitmap Resource ID = 1001, Usable = 1)
#define MainUnnamed1002Label                      1002	//(Left Origin = 53, Top Origin = 10, Usable = 1, Font = Bold)
#define MainUnnamed1003Label                      1003	//(Left Origin = 53, Top Origin = 25, Usable = 1, Font = Standard)
#define MainUnnamed1004Label                      1004	//(Left Origin = 55, Top Origin = 41, Usable = 1, Font = Standard)
#define MainUnnamed1007Label                      1007	//(Left Origin = 22, Top Origin = 57, Usable = 1, Font = Standard)
#define MainUnnamed1008Label                      1008	//(Left Origin = 53, Top Origin = 57, Usable = 1, Font = Standard)


//	Resource: tSTL 1000
#define AppStringsStringList                      1000
//	Resource: PICT 1000
#define AppLogoBitmap                             1000
//	Resource: PICT 1001
#define MWLogoBitmap                              1001

