//	Header generated by Constructor for Palm OS¨ 1.5
//
//	Generated at 5:26:58 PM on Monday, February 14, 2000
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"Table Example"
//
//	Palm App Version: 		"1.0"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainHideRowsButton                        1003	//(Left Origin = 1, Top Origin = 147, Width = 50, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainHideColumnsButton                     1004	//(Left Origin = 56, Top Origin = 147, Width = 64, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainGrafittiShift              1005	//(Left Origin = 140, Top Origin = 147)
#define MainList                       1002	//(Left Origin = 120, Top Origin = 141, Width = 19, Usable = 0, Font = Standard, Visible Items = 0)
#define MainTable                      1001	//(Left Origin = 0, Top Origin = 16, Width = 160, Height = 121, Editable = 1, Rows = 11)


//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1105	//(Left Origin = 58, Top Origin = 133, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutEmailLabel                           1101	//(Left Origin = 30, Top Origin = 64, Usable = 1, Font = Standard)
#define AboutTitleLabel                           1102	//(Left Origin = 37, Top Origin = 21, Usable = 1, Font = Large)
#define AboutCopyrightLabel                       1103	//(Left Origin = 30, Top Origin = 52, Usable = 1, Font = Standard)
#define AboutVersionLabel                         1104	//(Left Origin = 54, Top Origin = 37, Usable = 1, Font = Standard)
#define AboutBlurb1Label                          1106	//(Left Origin = 36, Top Origin = 83, Usable = 1, Font = Standard)
#define AboutBlurb2Label                          1107	//(Left Origin = 12, Top Origin = 95, Usable = 1, Font = Standard)
#define AboutBlurb3Label                          1108	//(Left Origin = 12, Top Origin = 107, Usable = 1, Font = Standard)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: MBAR 1000
#define MainFormMenuBar                           1000

//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAboutTableExample              1000
