//	Header generated by Constructor for Palm OS¨ 1.5
//
//	Generated at 6:46:50 PM on Thursday, November 11, 1999
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"DrMcCoy"
//
//	Palm App Version: 		"3.0"



//	Resource: tFRM 1000
#define DrMcCoyMainForm                           1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define DrMcCoyMainExplanationLabel               1001	//(Left Origin = 2, Top Origin = 27, Usable = 1, Font = Standard)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1101
#define SaySomethingAlert                         1101
#define SaySomethingOK                            0

