//	Header generated by Constructor for Pilot 1.0.2
//
//	Generated at 10:41:24 AM on Friday, March 26, 1999
//
//	Generated for file: D:\CodeWarrior5\Symbol NDK Support\Samples\Client\FindMdb\Rsc\FindMdb.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALMPILOT;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Pilot App Name: 		"FindMdb"
//
//	Pilot App Version: 		"1.0"



//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainSubmitButton                          1004	//(Left Origin = 58, Top Origin = 123, Width = 41, Height = 12, Usable = 1, Anchor Left = 0, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainItemCodeField                         1003	//(Left Origin = 24, Top Origin = 85, Width = 132, Height = 13, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 50, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainStatusField                           1007	//(Left Origin = 24, Top Origin = 15, Width = 132, Height = 13, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 50, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainTitleField                            1008	//(Left Origin = 24, Top Origin = 33, Width = 132, Height = 13, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 50, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainDescField                             1009	//(Left Origin = 24, Top Origin = 48, Width = 132, Height = 13, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 50, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainISBNField                             1011	//(Left Origin = 24, Top Origin = 68, Width = 132, Height = 13, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 50, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainUnnamed1001Label                      1001	//(Left Origin = 3, Top Origin = 50, Usable = 1, Font = Standard)
#define MainUnnamed1002Label                      1002	//(Left Origin = 3, Top Origin = 84, Usable = 1, Font = Standard)
#define MainUnnamed1005Label                      1005	//(Left Origin = 3, Top Origin = 16, Usable = 1, Font = Standard)
#define MainUnnamed1006Label                      1006	//(Left Origin = 3, Top Origin = 33, Usable = 1, Font = Standard)
#define MainUnnamed1010Label                      1010	//(Left Origin = 3, Top Origin = 68, Usable = 1, Font = Standard)


//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1101	//(Left Origin = 60, Top Origin = 141, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutSymbolLogoBitMap                     1100	//(Left Origin = 1, Top Origin = 13, Bitmap Resource ID = 1100, Usable = 1)
#define AboutDecoderField                         1103	//(Left Origin = 78, Top Origin = 96, Width = 75, Height = 13, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define AboutScanManagerField                     1105	//(Left Origin = 100, Top Origin = 111, Width = 53, Height = 13, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define AboutRFDriverField                        1107	//(Left Origin = 90, Top Origin = 124, Width = 63, Height = 13, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define AboutDecoderLabel                         1102	//(Left Origin = 4, Top Origin = 96, Usable = 1, Font = Standard)
#define AboutScanManagerLabel                     1104	//(Left Origin = 4, Top Origin = 110, Usable = 1, Font = Standard)
#define AboutPortDriverLabel                      1106	//(Left Origin = 4, Top Origin = 124, Usable = 1, Font = Standard)
#define AboutCopyrightLabel                       1109	//(Left Origin = 4, Top Origin = 68, Usable = 1, Font = Standard)
#define AboutCopyrighttooLabel                    1110	//(Left Origin = 4, Top Origin = 82, Usable = 1, Font = Standard)


//	Resource: Talt 1000
#define BatteryErrorAlert                         1000
#define BatteryErrorOK                            0

//	Resource: Talt 1100
#define NotScanEnabledAlert                       1100
#define NotScanEnabledOK                          0

//	Resource: Talt 1200
#define GeneralAlert                              1200
#define GeneralOK                                 0

//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: MBAR 1000
#define MainMenuBar                               1000

//	Resource: MENU 1000
#define OptionsMenu                               1000
#define OptionsAbout                              1000	// Command Key: A

//	Resource: tSTR 1000
#define MainFormHelpString                        1000	// "Test and Control of SE 1223 Scanner using SSI. Configure SE 1223 as follows to operate correctly.  This may be done using Parameter Barcodes.   1. Set All Defaults Parameter 2. Triggering Mode = HOST 3. Send Packeted Decode Data"

//	Resource: PICT 1100
#define SymbolLogoBitmap                          1100